project_id = "killbxwghyadhjtycwyn"

[functions.ai-assistant]
verify_jwt = false

[functions.search-gifs]
verify_jwt = false

[functions.send-scheduled-push]
verify_jwt = false

[functions.protocolo-145-ai]
verify_jwt = false

[functions.mente-poderosa-ai]
verify_jwt = false

[functions.daily-devotional]
verify_jwt = false

[functions.nutricionista-ai]
verify_jwt = false
