/**
 * 366 citações diárias de Louise Hay e Joyce Meyer.
 * Cada frase inclui a atribuição da autora.
 */
export const dailyQuotes: string[] = [
  // ══════════════════════════════════════════
  // LOUISE HAY (183 citações)
  // ══════════════════════════════════════════
  "Eu me amo e me aceito exatamente como sou. — Louise Hay",
  "Cada pensamento que penso está criando o meu futuro. — Louise Hay",
  "Eu mereço o melhor e aceito o melhor agora. — Louise Hay",
  "A vida me ama e eu estou segura. — Louise Hay",
  "Eu me aprovo e me aceito. Estou em paz. — Louise Hay",
  "Libero o passado com facilidade e confio no processo da vida. — Louise Hay",
  "Estou disposta a mudar e a crescer. — Louise Hay",
  "A vida me apoia em todos os sentidos possíveis. — Louise Hay",
  "O ponto de poder está sempre no momento presente. — Louise Hay",
  "Eu solto toda resistência e permito que o bem entre na minha vida. — Louise Hay",
  "Eu me recuso a me criticar. Eu me amo e me aprovo. — Louise Hay",
  "O amor é a maior força curativa do universo. — Louise Hay",
  "Eu perdoo a todos e me liberto do passado com alegria. — Louise Hay",
  "Meu corpo é saudável, minha mente é brilhante, minha alma é serena. — Louise Hay",
  "Estou aberta e receptiva a todas as coisas boas e maravilhosas da vida. — Louise Hay",
  "Sou uma expressão única e maravilhosa da vida. — Louise Hay",
  "A abundância flui para mim de todas as direções. — Louise Hay",
  "Eu crio a minha própria realidade com os meus pensamentos. — Louise Hay",
  "Eu escolho pensamentos que me fazem sentir bem. — Louise Hay",
  "A gratidão transforma o que eu tenho em suficiente e mais. — Louise Hay",
  "Cada dia é uma nova oportunidade de criar algo maravilhoso. — Louise Hay",
  "Confio na sabedoria infinita que guia meus passos. — Louise Hay",
  "Eu me permito ser feliz agora, neste exato momento. — Louise Hay",
  "Solto a necessidade de aprovação dos outros. — Louise Hay",
  "Sou merecedora de amor e sou digna de todo o bem. — Louise Hay",
  "A prosperidade é meu direito divino e eu a aceito agora. — Louise Hay",
  "Eu atraio pessoas amorosas e situações positivas para minha vida. — Louise Hay",
  "Cada célula do meu corpo vibra com energia e saúde. — Louise Hay",
  "Meu coração está aberto para dar e receber amor livremente. — Louise Hay",
  "Eu me liberto de toda culpa e vergonha do passado. — Louise Hay",
  "A cada respiração, inspiro confiança e expiro todo medo. — Louise Hay",
  "Estou em paz com minha história e animada com meu futuro. — Louise Hay",
  "Sou a criadora da minha vida e construo seus alicerces com amor. — Louise Hay",
  "Eu escolho ver o melhor em cada situação e em cada pessoa. — Louise Hay",
  "Solto o controle e confio no fluxo perfeito da vida. — Louise Hay",
  "Declaro paz e harmonia dentro de mim e ao meu redor. — Louise Hay",
  "Minha mente é um jardim — eu escolho plantar flores. — Louise Hay",
  "O amor que dou ao mundo retorna para mim multiplicado. — Louise Hay",
  "Eu sou capaz de lidar com tudo que a vida me apresenta. — Louise Hay",
  "Estou em harmonia com todas as pessoas ao meu redor. — Louise Hay",
  "Quando realmente nos amamos, tudo na vida funciona. — Louise Hay",
  "Eu não fixo minha mente em limitações. Eu fixo em possibilidades infinitas. — Louise Hay",
  "Meu futuro é glorioso e cheio de alegria. — Louise Hay",
  "Eu estou no lugar certo, na hora certa, fazendo a coisa certa. — Louise Hay",
  "Todos os meus relacionamentos são amorosos e harmoniosos. — Louise Hay",
  "Eu atraio somente experiências maravilhosas para minha vida. — Louise Hay",
  "Eu sou uma pessoa maravilhosa e mereço o melhor da vida. — Louise Hay",
  "A mudança é a lei natural da vida e eu aceito a mudança com alegria. — Louise Hay",
  "Eu confio no processo da vida. Estou segura. — Louise Hay",
  "Minha prosperidade interior se reflete no meu mundo exterior. — Louise Hay",
  "Eu libero toda necessidade de doença e fraqueza. — Louise Hay",
  "Hoje me liberto de velhos padrões negativos de pensamento. — Louise Hay",
  "Eu me permito viver a vida plenamente. — Louise Hay",
  "Nenhuma pessoa, lugar ou coisa tem poder sobre mim. — Louise Hay",
  "Meus pensamentos de hoje criam meu amanhã maravilhoso. — Louise Hay",
  "Eu fluo com a vida com facilidade e alegria. — Louise Hay",
  "Eu sou linda e todos me amam. Eu irradio saúde e felicidade. — Louise Hay",
  "Eu libero todas as expectativas. Estou livre para ser eu. — Louise Hay",
  "Estou aberta a receber toda a abundância do universo. — Louise Hay",
  "Eu me perdoo por não ser perfeita. — Louise Hay",
  "A sabedoria e a inteligência guiam cada passo meu. — Louise Hay",
  "Eu me trato com gentileza e paciência. — Louise Hay",
  "Hoje escolho a paz em vez da preocupação. — Louise Hay",
  "Minha vida é cheia de alegria e abundância. — Louise Hay",
  "Eu me liberto do medo e abraço o amor. — Louise Hay",
  "A vida é simples e fácil. Tudo o que preciso vem a mim no tempo perfeito. — Louise Hay",
  "Eu amo e aprovo cada parte de quem eu sou. — Louise Hay",
  "Eu estou em paz com todos ao meu redor e comigo mesma. — Louise Hay",
  "Eu transformo cada experiência negativa em uma lição de vida. — Louise Hay",
  "Sou grata por tudo o que tenho e por tudo o que está por vir. — Louise Hay",
  "Eu mereço uma vida maravilhosa e plena. — Louise Hay",
  "Eu me amo incondicionalmente. — Louise Hay",
  "Deixo ir o que não me serve mais com amor e gratidão. — Louise Hay",
  "Cada momento da minha vida é perfeitamente orquestrado pelo universo. — Louise Hay",
  "Eu sou uma pessoa próspera em todas as áreas da minha vida. — Louise Hay",
  "Eu perdoo facilmente e me liberto com amor. — Louise Hay",
  "Meus relacionamentos são baseados em respeito mútuo e amor. — Louise Hay",
  "Eu estou disposta a ver a vida de uma maneira diferente. — Louise Hay",
  "A paz interior é minha meta e eu a alcanço a cada dia. — Louise Hay",
  "Eu reconheço meu próprio valor. Sou maravilhosa. — Louise Hay",
  "Hoje é um dia magnífico para estar viva. — Louise Hay",
  "Eu me liberto da necessidade de ter razão. Prefiro ser feliz. — Louise Hay",
  "Eu expresso minha criatividade livremente e com alegria. — Louise Hay",
  "A alegria é minha bússola e eu a sigo fielmente. — Louise Hay",
  "Quanto mais gratidão eu sinto, mais razões para ser grata aparecem. — Louise Hay",
  "Meu trabalho é uma expressão do meu amor pela vida. — Louise Hay",
  "Eu solto a raiva e escolho a compreensão. — Louise Hay",
  "Hoje me abro para experiências novas e emocionantes. — Louise Hay",
  "Sou digna de amor, respeito e abundância infinita. — Louise Hay",
  "Eu estou rodeada de amor. Tudo está bem. — Louise Hay",
  "Eu me liberto de padrões alimentares negativos com amor. — Louise Hay",
  "A vida é boa e eu estou disposta a aproveitá-la. — Louise Hay",
  "Eu confio nos meus instintos e sigo minha intuição. — Louise Hay",
  "Eu sou forte, sábia e capaz de enfrentar qualquer desafio. — Louise Hay",
  "Eu mereço ter saúde perfeita agora. — Louise Hay",
  "Estou em paz com meu corpo e grata por tudo o que ele faz por mim. — Louise Hay",
  "Eu confio que tudo se resolve para o meu maior bem. — Louise Hay",
  "Eu sou a única pessoa que pensa na minha mente e escolho pensamentos de amor. — Louise Hay",
  "A abundância é o meu estado natural de ser. — Louise Hay",
  "Cada experiência da minha vida contribui para meu crescimento. — Louise Hay",
  "Eu solto o passado e vivo plenamente o presente. — Louise Hay",
  "Eu sou grata pelo milagre do meu corpo. — Louise Hay",
  "Hoje escolho ver a beleza em todas as coisas. — Louise Hay",
  "Meus sonhos são válidos e estão se manifestando agora. — Louise Hay",
  "Eu me permito crescer e evoluir constantemente. — Louise Hay",
  "Eu sou um ímã para coisas boas e maravilhosas. — Louise Hay",
  "O universo me provê tudo o que preciso em abundância. — Louise Hay",
  "Eu me aceito completamente neste momento. — Louise Hay",
  "Cada dia me torno mais forte, mais sábia e mais amorosa. — Louise Hay",
  "Eu me permito descansar e renovar minha energia. — Louise Hay",
  "O meu suprimento é infinito e vem de fontes inesperadas. — Louise Hay",
  "Eu danço com a vida e a vida dança comigo. — Louise Hay",
  "Hoje libero toda dor do passado e abraço a cura. — Louise Hay",
  "Eu escolho ser feliz. A felicidade é minha escolha diária. — Louise Hay",
  "Meus pensamentos são meus aliados, não meus inimigos. — Louise Hay",
  "Eu honro quem eu sou e quem estou me tornando. — Louise Hay",
  "A vida me surpreende com suas bênçãos todos os dias. — Louise Hay",
  "Eu me liberto de toda amargura e ressentimento. — Louise Hay",
  "Sou um canal de amor e paz no mundo. — Louise Hay",
  "Minha saúde melhora a cada dia que passa. — Louise Hay",
  "Eu confio que a vida cuida de mim perfeitamente. — Louise Hay",
  "Sou livre para ser autenticamente eu mesma. — Louise Hay",
  "Eu substituo o medo por fé e a dúvida por confiança. — Louise Hay",
  "Hoje é o dia mais importante da minha vida. — Louise Hay",
  "Meu coração transborda de gratidão e amor. — Louise Hay",
  "Eu vejo oportunidades onde antes via obstáculos. — Louise Hay",
  "A paz começa dentro de mim e se espalha pelo mundo. — Louise Hay",
  "Eu sou mais do que suficiente, exatamente como sou. — Louise Hay",
  "Mereço uma vida abundante em todas as suas formas. — Louise Hay",
  "Eu me liberto da necessidade de comparação. Sou única. — Louise Hay",
  "Cada célula do meu corpo responde aos meus pensamentos amorosos. — Louise Hay",
  "Estou segura ao expressar meus sentimentos. — Louise Hay",
  "Eu abraço a incerteza como uma aventura emocionante. — Louise Hay",
  "Sou grata por este novo dia cheio de possibilidades. — Louise Hay",
  "Eu me permito receber com a mesma alegria que dou. — Louise Hay",
  "A cura está acontecendo no meu corpo neste momento. — Louise Hay",
  "Eu planto sementes de bondade e colho uma vida plena. — Louise Hay",
  "Minha voz merece ser ouvida. Eu me expresso com confiança. — Louise Hay",
  "Cada obstáculo é um degrau para meu crescimento. — Louise Hay",
  "Eu acolho todas as minhas emoções com compaixão. — Louise Hay",
  "O dinheiro flui para mim livremente e eu o uso com sabedoria. — Louise Hay",
  "Estou criando uma vida que amo profundamente. — Louise Hay",
  "Eu solto a necessidade de perfeição e abraço o progresso. — Louise Hay",
  "A alegria de viver me preenche completamente. — Louise Hay",
  "Eu me relaciono com os outros de coração aberto. — Louise Hay",
  "Sou merecedora de todas as bênçãos que a vida me oferece. — Louise Hay",
  "Eu transformo meus medos em combustível para meu crescimento. — Louise Hay",
  "O perdão me liberta e me cura profundamente. — Louise Hay",
  "Eu me amo o suficiente para dizer não ao que não me serve. — Louise Hay",
  "Cada manhã trago novas possibilidades ilimitadas. — Louise Hay",
  "Eu me entrego à vida com confiança e serenidade. — Louise Hay",
  "Minha intuição me guia com perfeição divina. — Louise Hay",
  "Eu mereço tempo para cuidar de mim mesma. — Louise Hay",
  "A simplicidade é o caminho para a verdadeira felicidade. — Louise Hay",
  "Eu celebro minhas conquistas, grandes e pequenas. — Louise Hay",
  "Estou conectada com a sabedoria infinita dentro de mim. — Louise Hay",
  "Eu solto a pressa e confio no tempo divino de cada coisa. — Louise Hay",
  "Minha presença é um presente para o mundo. — Louise Hay",
  "Eu permito que o amor guie todas as minhas decisões. — Louise Hay",
  "A beleza da vida me enche de admiração todos os dias. — Louise Hay",
  "Eu me liberto do peso de expectativas alheias. — Louise Hay",
  "Sou a protagonista da minha história e ela é linda. — Louise Hay",
  "Eu nutro meu corpo, minha mente e meu espírito com amor. — Louise Hay",
  "O passado não define quem eu sou hoje. — Louise Hay",
  "Eu me permito sonhar grande e sem limites. — Louise Hay",
  "A bondade que espalho retorna multiplicada. — Louise Hay",
  "Eu sou resiliente e supero qualquer adversidade. — Louise Hay",
  "Minha vida é uma obra-prima em constante criação. — Louise Hay",
  "Eu confio no timing perfeito do universo para mim. — Louise Hay",
  "Hoje deixo a luz do amor iluminar cada canto da minha vida. — Louise Hay",
  "Eu me aceito sem julgamento e sem condições. — Louise Hay",
  "A compaixão que tenho por mim se estende a todos. — Louise Hay",
  "Eu cresço através do amor, nunca através do medo. — Louise Hay",
  "Minha energia positiva atrai resultados maravilhosos. — Louise Hay",
  "Eu estou pronta para o próximo capítulo incrível da minha vida. — Louise Hay",
  "A gentileza comigo mesma é minha maior força. — Louise Hay",
  "Eu me liberto de toda ansiedade e abraço a tranquilidade. — Louise Hay",
  "Sou guiada pela luz interior que nunca se apaga. — Louise Hay",
  "Eu transformo desafios em oportunidades com graça. — Louise Hay",
  "Minha vida reflete o amor que carrego no coração. — Louise Hay",
  "Eu sou completa, inteira e plena exatamente como sou. — Louise Hay",

  // ══════════════════════════════════════════
  // JOYCE MEYER (183 citações)
  // ══════════════════════════════════════════
  "Você não pode ter uma vida positiva com uma mente negativa. — Joyce Meyer",
  "Não tenha medo de dar um passo de fé. Deus está com você. — Joyce Meyer",
  "Preocupação é como uma cadeira de balanço: te dá algo para fazer, mas não te leva a lugar algum. — Joyce Meyer",
  "Quando você é positiva, coisas boas acontecem. — Joyce Meyer",
  "Coragem não é a ausência de medo. É seguir em frente com a presença dele. — Joyce Meyer",
  "A paciência não é simplesmente a habilidade de esperar. É como nos comportamos enquanto esperamos. — Joyce Meyer",
  "Suas emoções não precisam controlar suas ações. — Joyce Meyer",
  "Você pode sofrer a dor da mudança ou sofrer a dor de nunca mudar. A escolha é sua. — Joyce Meyer",
  "Deus não pede que você resolva tudo. Ele pede que confie Nele. — Joyce Meyer",
  "Deixe Deus trabalhar, porque quando Deus trabalha, tudo funciona. — Joyce Meyer",
  "Quando alguém te tratar mal, ore por essa pessoa. A oração muda as coisas. — Joyce Meyer",
  "A confiança em Deus é o segredo para uma vida sem ansiedade. — Joyce Meyer",
  "Você é uma obra-prima em progresso. Deus ainda não terminou com você. — Joyce Meyer",
  "Não espere sentir vontade de fazer a coisa certa. Faça a coisa certa e os sentimentos virão. — Joyce Meyer",
  "A sua vida pode ser diferente se você simplesmente começar a pensar diferente. — Joyce Meyer",
  "Ninguém pode arruinar o seu dia sem a sua permissão. — Joyce Meyer",
  "Deus tem um plano incrível para a sua vida. Não desista. — Joyce Meyer",
  "A gratidão abre a porta para mais bênçãos na sua vida. — Joyce Meyer",
  "Você não precisa ter todas as respostas. Você precisa conhecer Quem tem. — Joyce Meyer",
  "A fé é crer que algo vai acontecer antes de você ver acontecer. — Joyce Meyer",
  "Pare de se preocupar com o que as pessoas pensam de você. Viva para Deus. — Joyce Meyer",
  "Todas as vezes que perdoamos, desafiamos o passado e destrancamos o futuro. — Joyce Meyer",
  "A melhor coisa que você pode fazer pelo seu futuro é cuidar do presente. — Joyce Meyer",
  "Não olhe para onde você esteve. Olhe para onde você está indo. — Joyce Meyer",
  "Você é especial e valiosa. Não permita que ninguém te diga o contrário. — Joyce Meyer",
  "A oração é a chave da manhã e a tranca da noite. — Joyce Meyer",
  "Comece cada dia com um coração grato e termine com um coração em paz. — Joyce Meyer",
  "Você nunca está além do alcance da graça de Deus. — Joyce Meyer",
  "A preocupação é fé em ação na direção errada. — Joyce Meyer",
  "Quando sentir que não aguenta mais, lembre-se: com Deus você pode tudo. — Joyce Meyer",
  "Não fique presa ao que deu errado. Foque no que pode dar certo agora. — Joyce Meyer",
  "Cada dia é uma chance de ser melhor do que ontem. Aproveite. — Joyce Meyer",
  "Deus é capaz de fazer infinitamente mais do que tudo o que pedimos ou pensamos. — Joyce Meyer",
  "Onde Deus guia, Ele provê. — Joyce Meyer",
  "Sua atitude determina sua altitude na vida. — Joyce Meyer",
  "Quando você confia em Deus, pode confiar no seu futuro. — Joyce Meyer",
  "Não permita que as circunstâncias determinem o seu estado emocional. — Joyce Meyer",
  "Quem confia em Deus não precisa ter medo de nada. — Joyce Meyer",
  "O perdão não é um sentimento. É uma decisão. — Joyce Meyer",
  "Você é mais forte do que pensa. Deus está ao seu lado. — Joyce Meyer",
  "O segredo da paz é confiar completamente em Deus. — Joyce Meyer",
  "Levante-se todas as manhãs com determinação e vá para a cama com satisfação. — Joyce Meyer",
  "Não importa quantas vezes você cai. O que importa é quantas vezes se levanta. — Joyce Meyer",
  "A presença de Deus transforma qualquer situação. — Joyce Meyer",
  "Você foi criada para um propósito maravilhoso. Nunca duvide disso. — Joyce Meyer",
  "A vida é muito curta para ser desperdiçada com reclamações. — Joyce Meyer",
  "Seu passado não é o seu destino. Deus tem planos novos para você. — Joyce Meyer",
  "A obediência traz bênçãos que vão além da nossa compreensão. — Joyce Meyer",
  "Escolha ser grata. A gratidão muda tudo. — Joyce Meyer",
  "Quando parece impossível, Deus está trabalhando nos bastidores. — Joyce Meyer",
  "Não deixe a amargura criar raízes no seu coração. — Joyce Meyer",
  "Confie no plano de Deus, mesmo quando você não entende o caminho. — Joyce Meyer",
  "O amor é a força mais poderosa do universo. Use-o generosamente. — Joyce Meyer",
  "Você não precisa carregar o peso do mundo. Entregue a Deus. — Joyce Meyer",
  "A ansiedade não esvazia o amanhã de suas tristezas, mas esvazia o hoje de suas forças. — Joyce Meyer",
  "Seja corajosa o suficiente para recomeçar quantas vezes forem necessárias. — Joyce Meyer",
  "Quando você muda a forma como vê as coisas, as coisas que você vê mudam. — Joyce Meyer",
  "Faça o que você pode e Deus fará o que você não pode. — Joyce Meyer",
  "A esperança é o combustível que mantém a alma em movimento. — Joyce Meyer",
  "Não desperdice sua dor. Use-a para ajudar alguém. — Joyce Meyer",
  "A alegria do Senhor é a minha força. — Joyce Meyer",
  "Você está mais perto da sua vitória do que imagina. Continue. — Joyce Meyer",
  "Cada dia com Deus é um dia cheio de possibilidades. — Joyce Meyer",
  "Quanto mais tempo você gasta com Deus, mais parecida com Ele você fica. — Joyce Meyer",
  "Não foque no problema. Foque na solução que Deus tem para você. — Joyce Meyer",
  "Deus não desperdiça nada. Ele usa tudo para o seu bem. — Joyce Meyer",
  "Acredite no impossível, porque com Deus tudo é possível. — Joyce Meyer",
  "A paz que ultrapassa todo entendimento é real e está disponível para você. — Joyce Meyer",
  "Seu valor não diminui porque alguém não consegue ver o que você vale. — Joyce Meyer",
  "Deus transforma cicatrizes em estrelas. Confie Nele. — Joyce Meyer",
  "Aprenda a dizer não sem se sentir culpada. É um ato de amor próprio. — Joyce Meyer",
  "A transformação começa de dentro para fora. Mude sua mente, mude sua vida. — Joyce Meyer",
  "O medo grita, mas a fé sussurra: vai dar tudo certo. — Joyce Meyer",
  "Deus está sempre fazendo algo novo. Esteja atenta. — Joyce Meyer",
  "A bondade é uma linguagem que todos entendem. Pratique diariamente. — Joyce Meyer",
  "Deus me ama incondicionalmente e isso é tudo o que preciso saber. — Joyce Meyer",
  "O descanso não é preguiça. É sabedoria. Descanse em Deus. — Joyce Meyer",
  "Você não precisa entender tudo. Basta confiar em Quem entende. — Joyce Meyer",
  "Quanto mais você agradece, mais motivos para agradecer aparecem. — Joyce Meyer",
  "Cada amanhecer é uma nova misericórdia de Deus sobre sua vida. — Joyce Meyer",
  "Não se compare com os outros. Sua jornada é única e especial. — Joyce Meyer",
  "Deus pode usar pessoas comuns para fazer coisas extraordinárias. — Joyce Meyer",
  "Não existe fracasso quando você tenta. O fracasso é não tentar. — Joyce Meyer",
  "A paz de Deus guarda o meu coração e a minha mente. — Joyce Meyer",
  "Tenha paciência consigo mesma. A transformação leva tempo. — Joyce Meyer",
  "Você é amada, aceita e completamente perdoada por Deus. — Joyce Meyer",
  "A vida com Deus é uma aventura. Abrace cada momento. — Joyce Meyer",
  "Solte o que não pode controlar e confie no que é maior que você. — Joyce Meyer",
  "Deus completa o que Ele começa. Ele não vai desistir de você. — Joyce Meyer",
  "A sabedoria vem de ouvir mais do que falar. — Joyce Meyer",
  "Faça o bem mesmo quando ninguém está olhando. Deus está. — Joyce Meyer",
  "Os sonhos de Deus para você são maiores que os seus próprios sonhos. — Joyce Meyer",
  "Não desista nos dias difíceis. São eles que te tornam mais forte. — Joyce Meyer",
  "A fidelidade de Deus é nova a cada manhã. — Joyce Meyer",
  "Viva um dia de cada vez. Cada dia tem sua própria graça. — Joyce Meyer",
  "Acreditar em si mesma é o primeiro passo para alcançar seus sonhos. — Joyce Meyer",
  "Deus está do seu lado. Se Ele é por você, quem será contra você? — Joyce Meyer",
  "Sorria. A alegria é contagiante e transforma o ambiente ao redor. — Joyce Meyer",
  "Sua história ainda está sendo escrita por Deus. Os melhores capítulos estão por vir. — Joyce Meyer",
  "Quando tudo parecer escuro, lembre-se: as estrelas só brilham na escuridão. — Joyce Meyer",
  "Ore antes de agir. A sabedoria de Deus supera qualquer planejamento humano. — Joyce Meyer",
  "Você é a menina dos olhos de Deus. Nunca se esqueça disso. — Joyce Meyer",
  "A fé move montanhas. A dúvida cria muralhas. Escolha a fé. — Joyce Meyer",
  "Cada tempestade que você enfrentou te preparou para onde Deus quer te levar. — Joyce Meyer",
  "Não meça seu valor pelo que os outros dizem. Meça pelo que Deus diz. — Joyce Meyer",
  "A verdadeira liberdade está em viver sem medo do julgamento dos outros. — Joyce Meyer",
  "Deus usa suas fraquezas para mostrar Sua força. — Joyce Meyer",
  "Comece hoje. Não espere o momento perfeito. O momento é agora. — Joyce Meyer",
  "O amor de Deus é inabalável. Nada pode separar você dele. — Joyce Meyer",
  "A disciplina de hoje é a liberdade de amanhã. — Joyce Meyer",
  "Deus está trabalhando mesmo quando você não consegue ver. — Joyce Meyer",
  "Você é mais do que vencedora através Daquele que te ama. — Joyce Meyer",
  "Não permita que a pressa roube sua paz. Descanse no tempo de Deus. — Joyce Meyer",
  "A oração não muda Deus. Muda quem ora. — Joyce Meyer",
  "Sua situação é temporária, mas o amor de Deus é eterno. — Joyce Meyer",
  "Quando você perde a esperança, olhe para cima. Deus nunca perde de vista você. — Joyce Meyer",
  "Cuide de si mesma como cuida dos outros. Você também merece atenção. — Joyce Meyer",
  "A fé não elimina os problemas, mas te dá força para enfrentá-los. — Joyce Meyer",
  "Não se preocupe com o futuro. Viva o presente com fé e gratidão. — Joyce Meyer",
  "Deus tem o hábito de transformar tragédias em triunfos. — Joyce Meyer",
  "Seja gentil com você mesma nos dias em que a vida parecer pesada. — Joyce Meyer",
  "O caminho pode ser longo, mas com Deus ao lado, vale a pena caminhar. — Joyce Meyer",
  "A coragem não é nunca ter medo. É ter medo e seguir em frente mesmo assim. — Joyce Meyer",
  "Pare de sobreviver e comece a viver. Deus quer o melhor para você. — Joyce Meyer",
  "Cada problema tem uma data de validade. Essa fase vai passar. — Joyce Meyer",
  "A felicidade não depende das circunstâncias, mas da sua perspectiva. — Joyce Meyer",
  "Deus cuida dos detalhes da sua vida com amor e precisão. — Joyce Meyer",
  "Quando você se sentir sozinha, lembre-se: Deus está mais perto do que sua respiração. — Joyce Meyer",
  "A mudança começa quando você decide que já sofreu demais. — Joyce Meyer",
  "Tenha coragem de ser imperfeita e graça para aceitar que está em construção. — Joyce Meyer",
  "Hoje é o dia de soltar o que te prende e abraçar o que te liberta. — Joyce Meyer",
  "Deus não te trouxe até aqui para te deixar. Confie. — Joyce Meyer",
  "A verdadeira beleza vem de um coração em paz com Deus. — Joyce Meyer",
  "Não reclame da chuva. Dance nela. Deus está renovando sua vida. — Joyce Meyer",
  "Você foi desenhada pelo Criador. Nenhum detalhe sobre você é acidental. — Joyce Meyer",
  "A melhor versão de você nasce quando você se rende ao plano de Deus. — Joyce Meyer",
  "Não se diminua para caber no mundo dos outros. Você foi feita para brilhar. — Joyce Meyer",
  "Deus restaura o que o inimigo roubou. Acredite na restauração. — Joyce Meyer",
  "A generosidade é a semente da abundância. Plante com alegria. — Joyce Meyer",
  "Cada pôr do sol é uma chance de recomeçar. Cada amanhecer é um presente de Deus. — Joyce Meyer",
  "A fé é a certeza de que Deus está no controle, mesmo no caos. — Joyce Meyer",
  "Confie menos nas suas próprias forças e mais na força de Deus. — Joyce Meyer",
  "O plano de Deus é sempre melhor do que nossos melhores planos. — Joyce Meyer",
  "Você é forte porque Deus vive em você. — Joyce Meyer",
  "Mesmo nas noites mais escuras, o sol sempre nasce de novo. — Joyce Meyer",
  "A oração é a respiração da alma. Respire profundamente. — Joyce Meyer",
  "Não importa como você se sente hoje. Deus está ao seu lado amanhã também. — Joyce Meyer",
  "Viver com propósito é a maior aventura que existe. — Joyce Meyer",
  "Deus não te deu um espírito de medo, mas de poder, amor e equilíbrio. — Joyce Meyer",
  "A paz verdadeira não depende de tudo estar bem. Depende de saber que Deus cuida de tudo. — Joyce Meyer",
  "Cada lágrima que você derramou está guardada nas mãos de Deus. — Joyce Meyer",
  "O impossível é especialidade de Deus. — Joyce Meyer",
  "Não tenha vergonha da sua história. Ela vai inspirar alguém. — Joyce Meyer",
  "Deus é fiel mesmo quando nós não somos. Essa é Sua graça. — Joyce Meyer",
  "Escolha a alegria, não porque tudo é perfeito, mas porque Deus é bom. — Joyce Meyer",
  "Sua vitória não é sobre você. É sobre todos que serão abençoados através de você. — Joyce Meyer",
  "A esperança em Deus nunca decepciona. Segure-se nela. — Joyce Meyer",
  "Não olhe para trás. Você não está indo naquela direção. — Joyce Meyer",
  "Deus faz novas todas as coisas. Inclusive você. Especialmente você. — Joyce Meyer",
  "A vida é uma dádiva. Não a desperdice com ingratidão. — Joyce Meyer",
  "Caminhe com fé, mesmo quando não puder ver o caminho inteiro. — Joyce Meyer",
  "Deus te conhece pelo nome e te ama sem medida. — Joyce Meyer",
  "Quando você confia em Deus, até as derrotas se transformam em vitórias. — Joyce Meyer",
  "Não se apresse em resolver tudo. Algumas coisas só Deus pode fazer. — Joyce Meyer",
  "A vida com propósito é a vida que vale a pena viver. — Joyce Meyer",
  "Agradeça pelo que tem enquanto trabalha pelo que deseja. — Joyce Meyer",
  "A graça de Deus é suficiente para cada momento da sua vida. — Joyce Meyer",
  "Você não é o que aconteceu com você. Você é o que escolhe se tornar. — Joyce Meyer",
  "Deus está escrevendo uma história linda com a sua vida. Confie no Autor. — Joyce Meyer",
  "Cada desafio é uma chance de ver Deus agir poderosamente. — Joyce Meyer",
  "Quando a preocupação bater à porta, deixe a fé atender. — Joyce Meyer",
  "Você é preciosa aos olhos de Deus. Viva como tal. — Joyce Meyer",
  "A maior conquista é fazer paz consigo mesma. — Joyce Meyer",
  "Deus não promete dias fáceis, mas promete estar presente em todos eles. — Joyce Meyer",
  "Respire fundo. Deus está no controle. — Joyce Meyer",
];
