/**
 * 365+ frases inspiradoras para o hub de Manifestação Diária.
 * Inclui frases inspiradas em Louise Hay, Joyce Meyer e sabedoria universal.
 */
export const dailyQuotes: string[] = [
  // — Louise Hay —
  "Eu me amo e me aceito exatamente como sou.",
  "Cada pensamento que penso está criando o meu futuro.",
  "Estou disposta a mudar e a crescer.",
  "Eu mereço o melhor e aceito o melhor agora.",
  "Libero o passado com facilidade e confio no processo da vida.",
  "Eu me aprovo. Eu me amo. Estou em paz.",
  "A vida me apoia em todos os sentidos.",
  "Estou segura no universo e a vida me ama.",
  "Todas as minhas experiências são oportunidades de crescimento.",
  "Declaro paz e harmonia dentro de mim e ao meu redor.",
  "Eu sou capaz de lidar com tudo que a vida me apresenta.",
  "Escolho pensamentos que me fazem sentir bem.",
  "Cada dia é uma nova oportunidade de criar algo maravilhoso.",
  "A abundância flui para mim de todas as direções.",
  "Eu solto toda resistência e permito que o bem entre na minha vida.",
  "Meu corpo é saudável, minha mente é brilhante e minha alma é serena.",
  "Estou aberta e receptiva a todas as coisas boas da vida.",
  "Eu perdoo a todos e me liberto do passado.",
  "A cada respiração, inspiro confiança e expiro medo.",
  "Sou uma expressão única da vida e sou merecedora de amor.",
  "Confio na sabedoria infinita que guia meus passos.",
  "Eu me recuso a me criticar. Eu me amo e me aprovo.",
  "O amor é a maior força curativa do universo.",
  "Deixo ir o que não me serve mais.",
  "Eu crio a vida que desejo com pensamentos positivos.",
  "Sou digna de tudo de bom que a vida tem a oferecer.",
  "Hoje escolho a alegria como minha companheira.",
  "Estou em harmonia com todas as pessoas ao meu redor.",
  "Meu coração está aberto para dar e receber amor.",
  "A gratidão transforma o que eu tenho em suficiente.",
  "Eu me permito ser feliz agora, neste momento.",
  "O universo conspira a meu favor.",
  "Eu escolho ver o melhor em cada situação.",
  "Solto o controle e confio no fluxo da vida.",
  "Sou uma mulher poderosa e cheia de luz.",
  "Cada célula do meu corpo vibra com energia e saúde.",
  "Eu me liberto de toda culpa e vergonha do passado.",
  "A prosperidade é meu direito divino.",
  "Eu atraio pessoas amorosas e situações positivas.",
  "Minha mente é um jardim — eu escolho plantar flores.",
  "Estou em paz com minha história e animada com meu futuro.",
  "O amor que dou ao mundo retorna para mim multiplicado.",
  "Eu sou a arquiteta da minha vida e construo com amor.",
  "Solto a necessidade de aprovação dos outros.",
  "Minha vida é um reflexo dos meus pensamentos mais profundos.",
  "Eu mereço um amor profundo e verdadeiro.",
  "A felicidade é uma escolha e eu a faço agora.",
  "Confio que tudo acontece no momento certo.",
  "Eu celebro cada pequena vitória no meu caminho.",
  "Sou forte, sou corajosa, sou merecedora.",

  // — Joyce Meyer —
  "Deus não está procurando pessoas perfeitas, mas sim disponíveis.",
  "Não permita que o medo do amanhã roube a alegria de hoje.",
  "Você pode sofrer a dor da mudança ou a dor de nunca mudar.",
  "A confiança é silenciosa. As inseguranças são barulhentas.",
  "Comece a aproveitar a jornada, não apenas o destino.",
  "A sua mente é um campo de batalha — escolha bem os pensamentos.",
  "Preocupação é um desperdício de imaginação.",
  "Você não precisa ser perfeita para ser incrível.",
  "Deus te ama exatamente como você é, não como deveria ser.",
  "Grandes coisas acontecem para aqueles que não desistem.",
  "Não se compare com os outros — sua jornada é única.",
  "A paciência não é a capacidade de esperar, mas de manter uma boa atitude enquanto espera.",
  "Suas palavras têm poder. Use-as para construir, não para destruir.",
  "Quando você é grata, o medo desaparece e a abundância aparece.",
  "A verdadeira liberdade começa quando você perdoa.",
  "Coragem não é a ausência de medo, mas a decisão de seguir em frente apesar dele.",
  "Faça o que é certo, mesmo quando ninguém está olhando.",
  "Deus pode restaurar o que está quebrado e mudar para algo incrível.",
  "Cada novo dia é uma chance de recomeçar.",
  "Não desista de algo só porque é difícil. As melhores coisas da vida exigem esforço.",
  "Substitua a preocupação pela oração e a ansiedade pela confiança.",
  "Você é mais forte do que imagina e mais amada do que sabe.",
  "A gratidão muda sua perspectiva e transforma sua vida.",
  "Pare de tentar agradar a todos. Agrade a Deus e estará em paz.",
  "Você não está sozinha. Nunca esteve.",
  "O passado não define o seu futuro. Você pode recomeçar a qualquer momento.",
  "A alegria é uma decisão, não uma circunstância.",
  "Confie no processo, mesmo quando não entender o caminho.",
  "Faça o seu melhor e deixe Deus fazer o resto.",
  "Não olhe para trás. Você não está indo naquela direção.",
  "A fé é dar o primeiro passo mesmo quando não se vê a escada inteira.",
  "Onde Deus guia, Ele provê.",
  "A paz não é a ausência de problemas, mas a presença de Deus no meio deles.",
  "Você foi criada para um propósito grandioso.",
  "Permita-se descansar sem culpa. Até Deus descansou.",
  "A bondade pode mudar o mundo. Comece sendo gentil consigo mesma.",
  "Não se preocupe com o que você não pode controlar.",
  "Cada dia sem reclamar é um dia de vitória.",
  "A sua atitude determina a sua direção.",
  "Não espere se sentir pronta. Aja e a confiança virá.",
  "Deus trabalha mesmo quando você não vê.",

  // — Sabedoria Universal & Manifestação —
  "Você não precisa de mais uma técnica. Você precisa ser cuidada todos os dias.",
  "Manifestar não acontece apenas quando você visualiza. Acontece no jeito como você pensa, sente e se posiciona.",
  "A sua vibração é o convite que o universo lê antes de qualquer palavra que você diga.",
  "Gratidão não é só agradecer. É vibrar na frequência de quem já recebeu.",
  "Você já é a versão que deseja ser. Só precisa parar de duvidar disso.",
  "O universo não responde ao que você quer. Responde ao que você vibra.",
  "Cada pensamento é uma semente. Escolha plantar o que deseja colher.",
  "A abundância começa quando você para de contar o que falta e celebra o que já existe.",
  "Sua energia fala antes de você. Cuide dela como cuida do seu sonho mais bonito.",
  "Não espere o momento perfeito. Crie a vibração perfeita agora.",
  "Quando você muda a frequência, muda a realidade.",
  "Confie no tempo do universo. Ele sabe exatamente quando entregar o que é seu.",
  "Tudo sempre dá certo pra mim — repita até que seu corpo acredite.",
  "Você merece tudo aquilo que não consegue parar de imaginar.",
  "A melhor versão de você não está no futuro. Está em cada escolha que você faz agora.",
  "Solte o controle. O que é seu vai te encontrar no caminho.",
  "Sua intuição é a voz do seu Eu Superior. Aprenda a ouvi-la.",
  "Cada amanhecer é um recomeço. Use-o com intenção.",
  "Você não atrai o que quer, atrai o que você é. Seja magnética.",
  "A realidade que você deseja já existe. Alinhe-se a ela.",
  "Permita-se receber. Você já fez o suficiente para merecer.",
  "O impossível é só o possível que ainda não acreditaram.",
  "Sua história está sendo reescrita a cada pensamento consciente.",
  "Respire fundo. Você está exatamente onde precisa estar.",
  "A magia acontece quando você para de forçar e começa a fluir.",
  "Não subestime o poder de um dia vivido com presença.",
  "Você é a criadora da sua realidade. Crie com amor.",
  "Quando a dúvida aparecer, lembre-se: você já superou coisas que achou impossíveis.",
  "Seu brilho incomoda quem ainda não encontrou o próprio. Continue brilhando.",
  "Hoje é o dia perfeito pra manifestar algo extraordinário.",
  "A constância transforma intenção em realidade.",
  "O amor próprio é o primeiro passo para atrair amor verdadeiro.",
  "Você está mais perto do que imagina. Continue.",
  "A transformação começa na decisão de não aceitar menos do que você merece.",
  "Cuide dos seus pensamentos como cuida do seu corpo: com disciplina e carinho.",
  "A sua fé é mais forte que o seu medo.",
  "Tudo o que você precisa já está dentro de você.",
  "Quando você acredita, o universo se reorganiza para te atender.",
  "Não existe fracasso, apenas aprendizado disfarçado.",
  "Cada emoção é uma mensageira. Ouça sem julgar.",
  "O silêncio é onde a sabedoria fala mais alto.",
  "Permita-se sonhar grande. O universo sabe lidar com a grandeza.",
  "Gratidão é o ímã mais poderoso do universo.",
  "Você não precisa provar nada a ninguém, apenas a si mesma.",
  "Hoje eu me comprometo a ser a melhor versão de mim.",
  "O segredo da manifestação é sentir como se já tivesse acontecido.",
  "Abra espaço para o novo. Solte o que já cumpriu seu papel.",
  "Cada manhã é um convite para recomeçar com mais consciência.",
  "Onde há amor, há possibilidade infinita.",
  "Confie: o melhor ainda está por vir.",
  "Eu sou um ímã de coisas boas e oportunidades.",
  "A vida é um espelho. Sorria primeiro.",
  "Quando você vibra alto, nada de baixa vibração consegue te alcançar.",
  "O que você pratica diariamente molda quem você se torna.",
  "Sua voz interior sabe o caminho. Confie nela.",
  "A cura começa quando você para de fugir de si mesma.",
  "Não tenha medo de brilhar. O mundo precisa da sua luz.",
  "Toda grande conquista começou com a decisão de tentar.",
  "Respire. Acredite. Receba.",
  "Você é muito mais do que seus medos te fazem acreditar.",
  "A paz interior é o maior luxo que existe.",
  "Eu confio no meu poder de criar a vida que desejo.",
  "As cicatrizes contam a história de quem sobreviveu e floresceu.",
  "Viva com intenção. Ame com propósito. Brilhe sem pedir desculpas.",
  "Aquilo que é para você não vai te passar.",
  "A sua frequência é sua assinatura energética. Mantenha-a elevada.",
  "O que você semeia no invisível colhe no visível.",
  "Não existe coincidência. Existe sincronicidade.",
  "Tudo que você precisa para ser feliz já mora dentro de você.",
  "Escolha pensamentos que te elevem, não que te limitem.",
  "O perdão é um presente que você dá a si mesma.",
  "Celebre suas vitórias, por menores que pareçam.",
  "A disciplina é a ponte entre seus sonhos e sua realidade.",
  "Seu corpo é seu templo. Cuide dele com amor e respeito.",
  "Quando a tempestade passar, você vai perceber como ficou mais forte.",
  "Eu decreto que coisas boas estão a caminho.",
  "O universo ouve sua energia antes de ouvir suas palavras.",
  "Não se apresse. Tudo que é seu virá no tempo certo.",
  "A beleza verdadeira vem de dentro e irradia para fora.",
  "Você é uma obra em progresso, e isso é perfeitamente lindo.",
  "Cada desafio é uma aula disfarçada. Aprenda e siga em frente.",
  "Quando você se alinha com sua essência, milagres acontecem.",
  "Pare de pedir permissão para ser quem você é.",
  "A vida é generosa com quem é generosa consigo mesma.",
  "Eu honro minha jornada e confio nos meus próximos passos.",
  "Você é merecedora de todas as bênçãos que estão chegando.",
  "A mudança começa com um único pensamento diferente.",
  "Não existe competição quando você está na sua própria pista.",
  "Transforme suas feridas em sabedoria.",
  "A sua história ainda está sendo escrita. Faça dela uma obra-prima.",
  "Eu me permito prosperar em todas as áreas da minha vida.",
  "O que parece impossível hoje será sua história de superação amanhã.",
  "Acredite: você foi feita para coisas grandiosas.",
  "A felicidade não é um destino, é o caminho.",
  "Eu sou grata por quem sou e por quem estou me tornando.",
  "O amor que você procura está procurando por você.",
  "Não negocie seus valores por aprovação alheia.",
  "Cada fim é um novo começo disfarçado.",
  "Eu escolho a leveza em vez do peso. A fé em vez do medo.",
  "O universo trabalha a seu favor, mesmo quando não parece.",
  "Você tem dentro de si tudo que precisa para ser feliz.",
  "Nunca subestime o poder de uma mulher determinada.",
  "Eu estou exatamente onde preciso estar neste momento.",
  "A coragem não grita. Às vezes é a voz quieta que diz: amanhã eu tento de novo.",
  "Minha história importa. Minha voz importa. Eu importo.",
  "Quando a vida parece pesada, lembre-se: até o diamante é feito sob pressão.",
  "Eu me recuso a desistir de mim mesma.",
  "A maior prova de amor próprio é não aceitar migalhas.",
  "O que você faz por si mesma hoje ecoa em todas as suas amanhãs.",
  "Eu decreto abundância sobre a minha vida.",
  "A fé move montanhas, mas a ação abre caminhos.",
  "Eu escolho ser feliz antes de ter motivos para isso.",
  "A vida é curta demais para viver a dos outros.",
  "Eu sou a protagonista da minha história.",
  "Onde há intenção, há transformação.",
  "Nada pode impedir uma mulher que decidiu brilhar.",
  "A sua energia é sagrada. Proteja-a.",
  "Eu atraio o que vibro. E eu vibro alto.",
  "Cada dia é uma chance de se reinventar.",
  "O melhor investimento que você pode fazer é em si mesma.",
  "Eu estou criando a vida dos meus sonhos, um dia de cada vez.",
  "Quanto mais grata, mais motivos para ser grata aparecem.",
  "Eu confio no plano divino para minha vida.",
  "Nenhuma tempestade dura para sempre.",
  "A verdadeira riqueza está em viver com propósito.",
  "Eu mereço paz, amor e abundância.",
  "A cada dia, me torno mais forte e mais sábia.",
  "O sol sempre volta a brilhar. E você também.",
  "Eu não preciso ser perfeita. Preciso ser autêntica.",
  "Tudo se transforma quando você muda sua perspectiva.",
  "Eu sou a resposta para as minhas próprias orações.",
  "O caminho pode ser longo, mas cada passo importa.",
  "Eu celebro quem eu sou e quem estou me tornando.",
  "A vida me surpreende positivamente todos os dias.",
  "Eu solto o passado e abraço o presente com amor.",
  "Minha alma sabe o caminho. Eu confio nela.",
  "Eu sou digna de uma vida extraordinária.",
  "Cada experiência me prepara para algo maior.",
  "O que eu busco também me busca.",
  "Eu caminho na direção dos meus sonhos com fé e determinação.",
  "A generosidade multiplica tudo que é bom na vida.",
  "Eu estou em paz comigo e com o mundo.",
  "O amor é a resposta para todas as perguntas.",
  "Eu me permito ser vulnerável e ainda assim, poderosa.",
  "A vida me ensina exatamente o que preciso aprender.",
  "Eu sou uma força da natureza.",
  "Cada dia sem comparação é um dia de liberdade.",
  "O universo cuida de mim com carinho e precisão.",
  "Eu sou merecedora de milagres diários.",
  "A verdadeira beleza é ser autenticamente você.",
  "Eu decreto que este é o meu melhor ano.",
  "Onde coloco minha atenção, coloco minha energia.",
  "Eu sou a mudança que quero ver no mundo.",
  "A leveza é uma escolha diária.",
  "Eu confio que tudo se resolve a meu favor.",
  "Nenhum sonho é grande demais quando a fé é maior que o medo.",
  "Eu estou alinhada com meu propósito.",
  "A minha paz vale mais do que qualquer discussão.",
  "Eu me entrego ao fluxo da vida com confiança.",
  "Tudo o que preciso já está a caminho.",
  "Eu sou resiliente, sou forte, sou completa.",
  "A felicidade mora nos detalhes. Eu escolho notá-los.",
  "Eu planto sementes de amor onde quer que eu vá.",
  "A minha vida é um presente e eu a vivo com gratidão.",
  "Eu mereço descanso tanto quanto mereço sucesso.",
  "O perdão me liberta para viver plenamente.",
  "Eu sou a minha melhor companhia.",
  "A cada novo dia, me apaixono mais pela vida.",
  "Eu sou grata pela mulher que me tornei.",
  "O amor próprio é a base de todos os meus relacionamentos.",
  "Eu decreto bênçãos e prosperidade sobre minha família.",
  "A minha jornada é única e perfeitamente alinhada.",
  "Eu me escolho todos os dias, sem culpa.",
  "O tempo que dedico a mim mesma nunca é tempo perdido.",
  "Eu me permito errar e aprender com leveza.",
  "A cada manhã, renovo meus votos com a vida.",
  "Eu sou uma bênção para todos ao meu redor.",
  "A intensidade da minha fé supera qualquer obstáculo.",
  "Eu caminho com graça, determinação e amor.",
  "O que é meu já está reservado. Eu só preciso confiar.",
  "A minha energia transforma ambientes e pessoas.",
  "Eu sou saudável, próspera e abençoada.",
  "Cada recomeço é uma prova de que sou mais forte do que penso.",
  "Eu acolho a incerteza como espaço de possibilidades.",
  "O mundo precisa do meu brilho. Eu me permito brilhar.",
  "A minha voz é poderosa e merece ser ouvida.",
  "Eu agradeço por cada lição, mesmo as difíceis.",
  "Hoje eu vivo com propósito e presença.",
  "O impossível é o que ninguém fez ainda. Eu posso ser a primeira.",
  "Eu me recuso a diminuir minha luz para caber na caixa dos outros.",
  "A minha paz interior é inabalável.",
  "Cada escolha consciente me aproxima da vida que desejo.",
  "Eu sou amada, protegida e guiada.",
  "A abundância é o meu estado natural.",
  "Eu honro os meus limites e celebro meus avanços.",
  "Meu coração é grato, minha mente é clara e meu espírito é leve.",
  "Eu decreto que coisas extraordinárias acontecem na minha vida.",
  "Sou uma mulher que transforma dor em sabedoria.",
  "A minha fé é maior que qualquer estatística.",
  "Eu solto o que não posso controlar e abraço o que posso criar.",
  "O universo me apoia em cada passo que dou.",
  "Eu sou a dona da minha narrativa.",
  "Amor, saúde e prosperidade fluem abundantemente para mim.",
  "Eu confio no meu instinto e nas minhas decisões.",
  "A melhor hora para brilhar é agora.",
  "Eu me perdoo completamente e sigo em frente com leveza.",
  "Cada respiração é uma afirmação de que estou viva e capaz.",
  "Eu sou muito mais do que meus erros do passado.",
  "A vida conspira para me fazer feliz.",
  "Eu sou a prioridade da minha própria vida.",
  "O meu futuro é brilhante porque eu estou construindo com amor.",
  "Eu decreto saúde perfeita para o meu corpo e minha mente.",
  "A minha gratidão é tão grande que não cabe em palavras.",
  "Eu sou uma mulher que inspira outras mulheres.",
  "O amor incondicional começa dentro de mim.",
  "Eu mereço uma vida leve, bonita e abundante.",
  "A minha história de superação vai inspirar gerações.",
  "Eu caminho na luz, mesmo quando o caminho parece escuro.",
  "Tudo que toco se transforma em ouro porque vibro na frequência certa.",
  "Eu sou inteira, sou suficiente, sou completa.",
  "A fé que carrego no coração ilumina qualquer escuridão.",
  "Eu sou uma manifestadora consciente da minha realidade.",
  "Cada dia é uma página em branco. Eu escrevo com amor.",
  "O universo me presenteia com exatamente o que preciso, quando preciso.",
  "Eu celebro minha evolução com orgulho e humildade.",
  "A minha presença é poderosa e transforma qualquer ambiente.",
  "Eu escolho viver com coragem, não com medo.",
  "Sou grata por cada amanhecer e cada chance de fazer diferente.",
  "Eu mereço relações saudáveis, recíprocas e amorosas.",
  "A cada dia, me conecto mais com minha essência divina.",
  "O que plantar com fé, colherei com abundância.",
  "Eu sou digna de receber tudo que o universo tem para mim.",
  "A minha luz interior nunca se apaga.",
  "Eu me permito viver em plenitude e alegria.",
  "O meu propósito é claro e meu coração está alinhado.",
  "Eu agradeço por esta vida extraordinária que estou criando.",
  "Nada pode me parar quando estou alinhada com meu propósito.",
  "Eu decreto paz, amor e harmonia em todos os setores da minha vida.",
  "A mulher que eu me tornei faria a menina que fui se orgulhar.",
  "Eu sou um canal de luz, amor e cura.",
  "Cada desafio superado me torna mais forte e mais sábia.",
  "Eu me comprometo a viver com autenticidade e propósito.",
  "A gratidão é a minha oração diária.",
  "Eu sou infinitamente amada pelo universo.",
  "O meu melhor dia ainda não aconteceu — e isso me emociona.",
  "Eu vivo na expectativa do extraordinário.",
  "Cada momento é sagrado e cheio de possibilidades.",
  "Eu sou a mulher dos meus próprios sonhos.",
  "A vida me surpreende quando eu paro de controlá-la.",
  "Eu irradio amor, confiança e beleza interior.",
  "O mundo é mais bonito com a minha presença nele.",
  "Eu estou pronta para receber todas as bênçãos que estão chegando.",
];
