import { useState, useEffect } from "react";
import { BookMarked, ChevronLeft, ChevronRight, History } from "lucide-react";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Button } from "@/components/ui/button";
import { format, subDays, addDays, isToday } from "date-fns";
import { ptBR } from "date-fns/locale";

type Religion =
  | "crista_catolica" | "crista_evangelica" | "crista_ortodoxa" | "crista_adventista"
  | "espirita" | "budista" | "islamica" | "judaica"
  | "hinduista" | "taoista" | "xintoista" | "sikh"
  | "umbanda" | "candomble" | "wicca" | "bahai"
  | "confucionista" | "jainista" | "zoroastrista"
  | "ateista" | "agnostica" | "universal";

const religionLabels: Record<Religion, string> = {
  crista_catolica: "✝️ Cristã Católica",
  crista_evangelica: "⛪ Cristã Evangélica",
  crista_ortodoxa: "☦️ Cristã Ortodoxa",
  crista_adventista: "📖 Adventista",
  espirita: "🌟 Espírita",
  budista: "☸️ Budista",
  islamica: "☪️ Islâmica",
  judaica: "✡️ Judaica",
  hinduista: "🕉️ Hinduísta",
  taoista: "☯️ Taoísta",
  xintoista: "⛩️ Xintoísta",
  sikh: "🪯 Sikh",
  umbanda: "🌊 Umbanda",
  candomble: "🥁 Candomblé",
  wicca: "🌙 Wicca",
  bahai: "⭐ Bahá'í",
  confucionista: "📚 Confucionista",
  jainista: "🙏 Jainista",
  zoroastrista: "🔥 Zoroastrista",
  ateista: "🧠 Ateísta/Humanista",
  agnostica: "🔍 Agnóstica",
  universal: "🌍 Espiritualidade Universal",
};

interface Devotional {
  verse: string;
  source: string;
  reflection: string;
  study: string;
  practice: string;
}

const devotionalsByReligion: Record<Religion, Devotional[]> = {
  crista_catolica: [
    { verse: "Porque eu sei os planos que tenho para vocês, diz o Senhor, planos de paz e não de mal, para vos dar um futuro e uma esperança.", source: "Jeremias 29:11", reflection: "Deus tem um plano específico para sua vida. Mesmo nos momentos de dúvida, Ele já preparou o caminho.", study: "Jeremias escreveu esta carta aos exilados na Babilônia, garantindo que o sofrimento seria temporário. O contexto mostra que Deus age mesmo quando não vemos. Na tradição católica, isso nos convida a confiar na Providência Divina.", practice: "Reze um Pai Nosso e ofereça suas preocupações a Deus. Depois, dê um passo concreto em direção a algo que você vem adiando." },
    { verse: "Eu sou o caminho, a verdade e a vida. Ninguém vem ao Pai senão por mim.", source: "João 14:6", reflection: "Jesus se apresenta como o único mediador. Seguir Seus passos é encontrar direção em meio ao caos.", study: "No contexto do Evangelho de João, Jesus consola os discípulos antes da crucificação. A Igreja Católica entende este versículo como fundamento da fé cristocêntrica e do caminho sacramental.", practice: "Participe da Eucaristia ou faça uma oração diante do Santíssimo. Peça a Jesus que ilumine suas decisões de hoje." },
    { verse: "Tudo posso naquele que me fortalece.", source: "Filipenses 4:13", reflection: "Paulo não falava de sucesso mundano, mas de contentamento em qualquer circunstância através de Cristo.", study: "Paulo escreveu da prisão, mostrando que a força de Cristo transcende circunstâncias. Na tradição católica, isso se conecta à virtude da fortaleza, um dos dons do Espírito Santo.", practice: "Identifique uma dificuldade atual. Ofereça-a em oração e peça a fortaleza do Espírito Santo para enfrentá-la." },
    { verse: "Vinde a mim, todos vós que estais cansados e sobrecarregados, e eu vos aliviarei.", source: "Mateus 11:28", reflection: "Jesus convida os que sofrem a encontrar descanso n'Ele. O alívio não é ausência de problemas, mas presença divina.", study: "Este convite de Jesus contrasta com o peso das leis farisaicas. Na espiritualidade católica, encontramos esse descanso na oração, nos sacramentos e na entrega confiante à vontade de Deus.", practice: "Faça um exame de consciência breve. Entregue a Maria, mãe de Jesus, aquilo que mais pesa em seu coração." },
    { verse: "O Senhor é meu pastor, nada me faltará.", source: "Salmo 23:1", reflection: "Deus cuida de cada detalhe da sua vida como um pastor atento cuida de suas ovelhas.", study: "O Salmo 23 é um dos mais conhecidos da Bíblia. Davi, que foi pastor antes de rei, usa sua experiência para descrever o cuidado divino. Na liturgia católica, é usado em funerais e momentos de consolação.", practice: "Leia o Salmo 23 completo em voz alta. Identifique uma área da sua vida onde você precisa confiar mais no cuidado de Deus." },
    { verse: "Sede fortes e corajosos. Não temais, nem vos assusteis, pois o Senhor, vosso Deus, estará convosco por onde quer que fordes.", source: "Josué 1:9", reflection: "A coragem cristã não é ausência de medo, mas a certeza da presença de Deus.", study: "Josué recebeu esta palavra ao assumir a liderança de Israel após Moisés. Na tradição católica, a coragem é fruto da confiança em Deus e da oração constante.", practice: "Enfrente hoje algo que você tem evitado por medo. Antes, peça a proteção de São Miguel Arcanjo." },
    { verse: "Amai-vos uns aos outros como eu vos amei.", source: "João 13:34", reflection: "O mandamento novo de Jesus é a essência do cristianismo: amar como Ele amou — sem condições.", study: "Jesus deu este mandamento na Última Ceia, antes de lavar os pés dos discípulos. O amor cristão (ágape) é sacrificial e incondicional, fundamento de toda a moral católica.", practice: "Pratique um ato de amor concreto por alguém que você tem dificuldade de amar. Ore por essa pessoa." },
  ],
  crista_evangelica: [
    { verse: "Porque pela graça sois salvos, por meio da fé; e isto não vem de vós, é dom de Deus.", source: "Efésios 2:8", reflection: "A salvação não depende de obras humanas, mas da graça de Deus recebida pela fé.", study: "Paulo escreve aos efésios enfatizando que a salvação é um presente gratuito. A teologia evangélica enfatiza a 'sola gratia' e 'sola fide' como pilares da fé reformada.", practice: "Agradeça a Deus pela salvação gratuita. Compartilhe com alguém hoje o que Jesus fez por você." },
    { verse: "Toda Escritura é inspirada por Deus e útil para o ensino, para a repreensão, para a correção e para a instrução na justiça.", source: "2 Timóteo 3:16", reflection: "A Bíblia é a Palavra viva de Deus, suficiente para guiar toda a vida cristã.", study: "Paulo instrui Timóteo sobre a autoridade das Escrituras. Na tradição evangélica, a Bíblia é a autoridade suprema (sola scriptura) para fé e prática.", practice: "Separe 15 minutos para leitura bíblica devocional. Escolha um livro e leia um capítulo com caderno ao lado para anotar o que Deus falar." },
    { verse: "Clama a mim, e responder-te-ei, e anunciar-te-ei coisas grandes e ocultas, que não sabes.", source: "Jeremias 33:3", reflection: "Deus promete responder quando clamamos. A oração não é monólogo, é diálogo com o Criador.", study: "Jeremias recebeu esta promessa enquanto estava preso. Deus responde mesmo quando estamos em situações limitantes. A vida de oração é central na espiritualidade evangélica.", practice: "Faça uma oração específica hoje. Anote o pedido e a data. Volte depois para ver como Deus respondeu." },
    { verse: "Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus.", source: "Isaías 41:10", reflection: "O medo perde poder quando lembramos que o Deus do universo está conosco.", study: "Isaías profetiza consolação ao povo de Israel. Na teologia evangélica, a presença de Deus é a base da segurança do crente — não as circunstâncias.", practice: "Escreva este versículo e cole em um lugar visível. Toda vez que sentir medo, leia em voz alta." },
    { verse: "Delight yourself in the Lord, and he will give you the desires of your heart.", source: "Salmo 37:4 — Deleita-te no Senhor e Ele te concederá os desejos do teu coração.", reflection: "Quando nos alinhamos com Deus, nossos desejos se transformam nos d'Ele.", study: "O salmista ensina que a verdadeira satisfação vem do relacionamento com Deus. Na prática evangélica, isso significa buscar primeiro o Reino de Deus (Mt 6:33).", practice: "Liste seus maiores desejos. Ore entregando cada um a Deus e peça que alinhe seu coração com a vontade d'Ele." },
    { verse: "O ladrão não vem senão a roubar, matar e destruir; eu vim para que tenham vida, e a tenham com abundância.", source: "João 10:10", reflection: "Jesus oferece vida plena — não apenas sobrevivência. A vida abundante é propósito, paz e plenitude.", study: "Jesus se compara ao Bom Pastor que dá a vida pelas ovelhas. A vida abundante na teologia evangélica inclui alegria, propósito e intimidade com Deus.", practice: "Identifique uma área onde o 'ladrão' está roubando sua paz. Declare em oração que Jesus veio para restaurar abundância nessa área." },
    { verse: "Mas os que esperam no Senhor renovarão as suas forças; subirão com asas como águias.", source: "Isaías 40:31", reflection: "Esperar no Senhor não é passividade — é confiança ativa enquanto Deus renova suas forças.", study: "Isaías encoraja o povo exausto. A águia renova suas penas em processo doloroso mas necessário. Na vida cristã, períodos de espera são tempos de renovação.", practice: "Se você está em um período de espera, ore declarando que suas forças estão sendo renovadas. Descanse em Deus hoje." },
  ],
  crista_ortodoxa: [
    { verse: "Deus é amor, e quem permanece no amor permanece em Deus, e Deus permanece nele.", source: "1 João 4:16", reflection: "Na teologia ortodoxa, o amor é a própria natureza de Deus — a Trindade é comunhão de amor.", study: "A teologia ortodoxa enfatiza a theosis (deificação) — tornar-se participante da natureza divina pelo amor. Os Padres da Igreja ensinam que o caminho para Deus é o caminho do amor.", practice: "Pratique a Oração de Jesus: 'Senhor Jesus Cristo, Filho de Deus, tem piedade de mim, pecador.' Repita por 5 minutos em silêncio." },
    { verse: "Adquire o Espírito da paz e milhares ao teu redor serão salvos.", source: "São Serafim de Sarov", reflection: "A transformação do mundo começa com a paz interior. A santidade pessoal irradia para os outros.", study: "São Serafim, um dos mais amados santos ortodoxos, ensinou que o objetivo da vida cristã é a aquisição do Espírito Santo. A hesychia (quietude interior) é central na espiritualidade ortodoxa.", practice: "Dedique 10 minutos ao silêncio contemplativo. Acenda uma vela se possível e permaneça na presença de Deus sem palavras." },
    { verse: "Onde está o teu tesouro, aí estará também o teu coração.", source: "Mateus 6:21", reflection: "Nossos investimentos de tempo e atenção revelam o que realmente valorizamos.", study: "Na tradição ortodoxa, o desapego material não é rejeição do mundo, mas liberdade interior. Os monges do Monte Athos vivem este princípio diariamente através da simplicidade.", practice: "Examine onde você investe mais tempo. Faça um jejum de algo supérfluo hoje e use esse tempo para oração ou leitura espiritual." },
    { verse: "Eu sou a luz do mundo. Quem me segue não andará nas trevas.", source: "João 8:12", reflection: "Cristo é a luz que dissipa toda escuridão interior. Segui-Lo é caminhar na clareza.", study: "Na liturgia ortodoxa, a luz tem papel central — velas, ícones iluminados, a Páscoa com a Luz Santa. A luz de Cristo transforma a pessoa de dentro para fora.", practice: "Contemple um ícone de Cristo por alguns minutos. Peça que Sua luz ilumine uma decisão ou situação difícil." },
    { verse: "Alegremo-nos e exultemos, porque o Senhor ressuscitou!", source: "Tropário Pascal Ortodoxo", reflection: "A Ressurreição é o centro da fé ortodoxa — Cristo venceu a morte e abriu caminho para a vida eterna.", study: "Na tradição ortodoxa, cada domingo é uma 'pequena Páscoa', celebração da Ressurreição. A alegria pascal permeia toda a espiritualidade ortodoxa.", practice: "Comece o dia com a exclamação pascal: 'Cristo ressuscitou!' Deixe essa verdade moldar sua perspectiva sobre os desafios de hoje." },
    { verse: "A oração é a respiração da alma.", source: "São João Crisóstomo", reflection: "Assim como o corpo precisa de ar, a alma precisa de oração constante para viver.", study: "São João Crisóstomo, um dos maiores Padres da Igreja, ensinou sobre a oração incessante. Na tradição ortodoxa, a Oração de Jesus é praticada como forma de 'orar sem cessar' (1 Ts 5:17).", practice: "Use um chotki (cordão de oração) ou conte nos dedos: reze a Oração de Jesus 33 vezes lentamente." },
    { verse: "Nada é impossível para quem crê.", source: "Marcos 9:23", reflection: "A fé ortodoxa ensina que a confiança em Deus move montanhas — não pela nossa força, mas pela graça.", study: "Este versículo vem do episódio da cura do menino possesso. Jesus ensina que a fé, mesmo pequena, conecta-nos ao poder infinito de Deus.", practice: "Identifique algo que parece impossível em sua vida. Entregue a Deus com fé simples e sincera." },
  ],
  crista_adventista: [
    { verse: "Lembra-te do dia de sábado para o santificar.", source: "Êxodo 20:8", reflection: "O sábado é um presente de Deus — um dia para descansar, renovar e reconectar-se com o Criador.", study: "Para os adventistas, o sábado (do pôr do sol de sexta ao pôr do sol de sábado) é memorial da criação e sinal da aliança com Deus. É tempo de adoração, natureza e comunidade.", practice: "Planeje seu próximo sábado de forma intencional: inclua adoração, tempo na natureza e desconexão das preocupações seculares." },
    { verse: "Acaso não sabeis que o vosso corpo é santuário do Espírito Santo?", source: "1 Coríntios 6:19", reflection: "Cuidar do corpo é um ato de adoração. Saúde física e espiritual caminham juntas.", study: "A mensagem de saúde é um dos pilares adventistas. Ellen White escreveu extensivamente sobre alimentação saudável, exercício e temperança como parte do plano de Deus para a saúde integral.", practice: "Faça uma refeição saudável hoje com gratidão. Beba água suficiente e inclua alguma atividade física como forma de honrar o templo do Espírito." },
    { verse: "Eis que venho sem demora; bem-aventurado aquele que guarda as palavras da profecia deste livro.", source: "Apocalipse 22:7", reflection: "A esperança na segunda vinda de Cristo motiva uma vida de preparo e serviço.", study: "O nome 'Adventista' vem da crença na segunda vinda (advento) de Cristo. Esta esperança escatológica não gera medo, mas motivação para viver com propósito e compartilhar o evangelho.", practice: "Viva hoje como se Jesus voltasse amanhã: resolva pendências, perdoe quem precisa, sirva com amor." },
    { verse: "Portanto, quer comais, quer bebais ou façais outra qualquer coisa, fazei tudo para a glória de Deus.", source: "1 Coríntios 10:31", reflection: "Cada escolha cotidiana — alimentação, trabalho, lazer — pode ser um ato de adoração.", study: "A filosofia adventista integra todas as áreas da vida sob a glória de Deus. A temperança e o equilíbrio são virtudes centrais que abrangem desde a dieta até o uso do tempo.", practice: "Antes de cada refeição hoje, agradeça a Deus. Escolha conscientemente alimentos que honrem seu corpo." },
    { verse: "Confiai no Senhor perpetuamente, pois o Senhor Deus é uma rocha eterna.", source: "Isaías 26:4", reflection: "Em um mundo de incertezas, Deus é a única rocha inabalável onde podemos ancorar nossa confiança.", study: "Isaías compara Deus a uma rocha — símbolo de estabilidade e proteção. Na teologia adventista, a confiança em Deus é reforçada pelo estudo profético que mostra Seu controle sobre a história.", practice: "Estude uma profecia bíblica cumprida (como Daniel 2). Deixe as evidências fortalecerem sua confiança no Deus que controla o futuro." },
    { verse: "Perto está o Senhor de todos os que o invocam, de todos os que o invocam em verdade.", source: "Salmo 145:18", reflection: "Deus está próximo — não distante. Basta invocá-Lo com sinceridade.", study: "A oração sincera é a ponte mais curta entre a alma e Deus. Na tradição adventista, o culto matinal e vespertino são práticas que mantêm essa conexão viva.", practice: "Estabeleça um momento fixo de oração hoje — manhã e noite. Ore com sinceridade sobre suas necessidades reais." },
    { verse: "Grandes coisas fez o Senhor por nós, e por isso estamos alegres.", source: "Salmo 126:3", reflection: "A gratidão é a resposta natural quando reconhecemos a ação de Deus em nossa vida.", study: "Este salmo celebra a restauração de Israel. Na vida adventista, reconhecer as bênçãos de Deus gera alegria e motivação para compartilhar com outros.", practice: "Escreva 5 grandes coisas que Deus fez por você. Compartilhe pelo menos uma com alguém hoje." },
  ],
  espirita: [
    { verse: "Fora da caridade não há salvação.", source: "Allan Kardec — O Evangelho Segundo o Espiritismo", reflection: "A verdadeira evolução espiritual se manifesta nos pequenos atos de bondade diários.", study: "Kardec ensina que a caridade vai além da esmola: é benevolência com todos, indulgência com as imperfeições alheias e perdão das ofensas. É a virtude que mais aproxima o homem de Deus.", practice: "Pratique um ato de caridade hoje — material, moral ou espiritual. Pode ser uma palavra de conforto, um perdão sincero ou ajuda concreta." },
    { verse: "Conhece-te a ti mesmo.", source: "O Livro dos Espíritos — questão 919", reflection: "O autoconhecimento é o primeiro passo para a reforma íntima e a evolução espiritual.", study: "Esta máxima socrática foi adotada pelo espiritismo como ferramenta essencial de crescimento. Kardec explica que conhecer nossas falhas é o primeiro passo para corrigi-las.", practice: "Reserve 10 minutos para um exame de consciência. Identifique um padrão de comportamento que gostaria de melhorar e trace um plano." },
    { verse: "Nascer, morrer, renascer ainda e progredir sempre, tal é a lei.", source: "Allan Kardec", reflection: "Cada vida é uma oportunidade de progresso. Os desafios são degraus na escada da evolução.", study: "A reencarnação é um dos pilares do espiritismo. Cada existência terrena é uma escola onde o espírito aprende lições específicas para sua evolução.", practice: "Identifique um desafio recorrente em sua vida. Reflita sobre qual lição espiritual ele pode conter e o que você pode aprender." },
    { verse: "A prece é um ato de adoração. Orar a Deus é pensar n'Ele, é aproximar-se d'Ele.", source: "O Evangelho Segundo o Espiritismo, cap. 27", reflection: "A prece não é um pedido de favores, mas uma elevação da alma em direção ao Criador.", study: "Kardec distingue a prece mental da verbal, ensinando que a qualidade da prece está na intenção e na elevação do pensamento, não nas palavras.", practice: "Faça uma prece silenciosa de 5 minutos. Concentre-se em elevar seus pensamentos, agradecer e pedir forças para sua reforma íntima." },
    { verse: "Sem estudo, o caminhante tropeça nas pedras da estrada.", source: "Emmanuel — psicografia de Chico Xavier", reflection: "O estudo constante ilumina o caminho espiritual e evita erros por ignorância.", study: "Na doutrina espírita, o estudo é tão importante quanto a prática da caridade. Os livros da codificação e as obras complementares são ferramentas de evolução moral e intelectual.", practice: "Leia um capítulo de um livro espírita hoje. Anote uma ideia que ressoou e reflita sobre como aplicá-la." },
    { verse: "Ninguém pode ver o Reino de Deus se não nascer de novo.", source: "João 3:3 — interpretação espírita", reflection: "A reencarnação é a oportunidade de recomeçar, aprender e evoluir através de múltiplas existências.", study: "O espiritismo interpreta este versículo como referência direta à reencarnação. Cada nova vida é um 'nascer de novo' com oportunidades renovadas de crescimento.", practice: "Reflita sobre situações que se repetem em sua vida. Que padrão kármico pode estar por trás? Como quebrá-lo com amor e consciência?" },
    { verse: "O mundo é uma escola e a vida é a lição.", source: "Chico Xavier", reflection: "Cada dia traz uma lição específica para nossa evolução. A vida é o maior professor.", study: "Chico Xavier, maior médium brasileiro, transmitiu mais de 400 livros. Sua mensagem central: a vida terrena é temporária e cada experiência tem propósito educativo para o espírito.", practice: "No final do dia, revise as situações vividas. Que lição cada uma trouxe? Anote em um diário espiritual." },
  ],
  budista: [
    { verse: "A paz vem de dentro de você mesmo. Não a procure à sua volta.", source: "Buda Shakyamuni", reflection: "A serenidade não depende das circunstâncias externas, mas da sua relação com o momento presente.", study: "O Budismo ensina que o sofrimento (dukkha) surge do apego e da busca externa por satisfação. A paz verdadeira é encontrada através da meditação e do cultivo da mente.", practice: "Medite por 10 minutos focando na respiração. Quando pensamentos surgirem, observe-os sem julgamento e retorne ao respiro." },
    { verse: "Milhares de velas podem ser acesas a partir de uma única vela, e a vida da vela não será encurtada.", source: "Dhammapada", reflection: "Compartilhar bondade e sabedoria não diminui sua luz — ao contrário, multiplica-a infinitamente.", study: "O Dhammapada é uma coleção de ensinamentos do Buda. Este verso ilustra o conceito de metta (amor benevolente) — quanto mais oferecemos, mais temos.", practice: "Ofereça uma palavra gentil ou um sorriso sincero a alguém hoje. Observe como isso transforma o ambiente." },
    { verse: "Não insista no passado, não sonhe com o futuro, concentre a mente no momento presente.", source: "Buda", reflection: "A atenção plena (mindfulness) ao agora dissolve a ansiedade do futuro e a tristeza do passado.", study: "A prática de sati (atenção plena) é central no Budismo. O Satipatthana Sutta descreve quatro fundamentos da atenção: corpo, sensações, mente e objetos mentais.", practice: "Escolha uma atividade cotidiana e faça com atenção plena: ao comer, sinta cada sabor; ao caminhar, sinta cada passo." },
    { verse: "Segurando a raiva é como beber veneno e esperar que a outra pessoa morra.", source: "Ensinamento Budista", reflection: "A raiva prejudica mais quem a carrega do que seu alvo. Soltar é um ato de autocompaixão.", study: "O Budismo ensina que a raiva (dosa) é um dos três venenos da mente, junto com a ignorância e a ganância. A prática de karuna (compaixão) é o antídoto.", practice: "Identifique uma mágoa que você carrega. Pratique a meditação de metta: 'Que eu esteja em paz. Que [pessoa] esteja em paz.'" },
    { verse: "Uma jarra se enche gota a gota.", source: "Dhammapada", reflection: "Grandes transformações acontecem através de pequenas ações consistentes, dia após dia.", study: "O Buda ensinou que a prática espiritual é gradual. Não há atalhos para a iluminação — cada pequeno ato de bondade, cada momento de consciência, contribui para o despertar.", practice: "Escolha uma pequena prática positiva para hoje e comprometa-se a fazê-la. Uma gota por vez enche a jarra da transformação." },
    { verse: "Você mesmo deve se esforçar. Os Budas apenas apontam o caminho.", source: "Dhammapada 276", reflection: "Ninguém pode trilhar o caminho por você. A libertação requer esforço pessoal e disciplina.", study: "O Budismo enfatiza a responsabilidade individual. O Nobre Caminho Óctuplo é o mapa, mas cada pessoa deve caminhar por si mesma.", practice: "Identifique uma área onde você está esperando que alguém resolva por você. Assuma a responsabilidade e dê o primeiro passo." },
    { verse: "Em toda adversidade, há a semente de um benefício equivalente ou maior.", source: "Ensinamento Budista sobre impermanência", reflection: "Nada é permanente — nem o sofrimento. Cada dificuldade carrega potencial de crescimento.", study: "Anicca (impermanência) é um dos três marcos da existência no Budismo. Entender que tudo muda liberta do apego ao sofrimento e ao prazer.", practice: "Reflita sobre uma dificuldade passada que se transformou em crescimento. Aplique essa perspectiva a um desafio atual." },
  ],
  islamica: [
    { verse: "Certamente com a dificuldade vem a facilidade.", source: "Alcorão, Surata 94:6 (Ash-Sharh)", reflection: "Toda provação carrega em si a semente do alívio. A paciência (sabr) é uma forma de adoração.", study: "Esta surata foi revelada para consolar o Profeta Muhammad (ﷺ) em tempos difíceis. A repetição da promessa (versículos 5-6) enfatiza a certeza divina.", practice: "Em momentos de dificuldade hoje, repita esta ayah. Faça uma du'a pedindo paciência e confiança em Allah." },
    { verse: "Allah não sobrecarrega nenhuma alma além da sua capacidade.", source: "Alcorão, 2:286 (Al-Baqarah)", reflection: "Você tem a força necessária para enfrentar cada teste. Allah conhece seus limites melhor que você.", study: "Esta é a última ayah da Surata Al-Baqarah, uma das mais importantes do Alcorão. Ela ensina que os testes de Allah são sempre proporcionais à capacidade do crente.", practice: "Faça uma du'a pedindo força e clareza. Depois, dê o primeiro passo prático em direção à solução do seu desafio." },
    { verse: "E quem deposita confiança em Allah, Ele lhe será suficiente.", source: "Alcorão, 65:3 (At-Talaq)", reflection: "Tawakkul é confiar em Allah depois de fazer o seu melhor esforço — é a união entre ação e fé.", study: "Tawakkul não é passividade, mas confiança ativa. O Profeta (ﷺ) ensinou: 'Amarre seu camelo e depois confie em Allah.' Ação e fé caminham juntas.", practice: "Planeje suas tarefas do dia com dedicação. Ao final, entregue os resultados a Allah com serenidade." },
    { verse: "Os servos do Misericordioso são aqueles que caminham sobre a terra com humildade.", source: "Alcorão, 25:63 (Al-Furqan)", reflection: "A humildade é marca dos verdadeiros servos de Allah. Caminhar com gentileza reflete grandeza interior.", study: "Esta ayah descreve as características dos 'Ibad ar-Rahman' (servos do Misericordioso). Humildade, paciência e oração noturna são suas marcas.", practice: "Pratique a humildade hoje: ouça mais do que fale, sirva sem esperar reconhecimento, trate todos com gentileza." },
    { verse: "Lembrai-vos de Mim e Eu Me lembrarei de vós.", source: "Alcorão, 2:152", reflection: "O dhikr (lembrança de Allah) é o caminho mais direto para a paz interior.", study: "A lembrança de Allah (dhikr) é considerada o melhor ato de adoração. O Profeta (ﷺ) disse: 'Não é com o dhikr de Allah que os corações encontram descanso?'", practice: "Faça dhikr por 5 minutos: 'SubhanAllah' (33x), 'Alhamdulillah' (33x), 'Allahu Akbar' (34x). Sinta a paz que vem da lembrança." },
    { verse: "Quem salva uma vida, é como se tivesse salvo toda a humanidade.", source: "Alcorão, 5:32 (Al-Ma'idah)", reflection: "Cada vida é sagrada no Islã. Pequenos atos de bondade podem ter impacto imenso.", study: "Esta ayah estabelece a santidade da vida humana no Islã. O conceito se estende a salvar pessoas da pobreza, ignorância, doença e desespero.", practice: "Ajude alguém hoje — pode ser com uma refeição, uma palavra de apoio ou orientação. Cada ato de bondade salva." },
    { verse: "Allah é belo e ama a beleza.", source: "Hadith — Sahih Muslim", reflection: "O Islã valoriza a beleza em todas as formas: caráter, ações, aparência e meio ambiente.", study: "Este hadith do Profeta (ﷺ) mostra que a beleza é um atributo divino. Cuidar da aparência, manter a limpeza e embelezar o ambiente são formas de adoração.", practice: "Organize e embeleze seu espaço hoje. Cuide de sua aparência com intenção de agradar a Allah." },
  ],
  judaica: [
    { verse: "Ouve, ó Israel: o Senhor nosso Deus, o Senhor é um.", source: "Deuteronômio 6:4 (Shemá Israel)", reflection: "A unidade de Deus nos lembra que tudo está conectado. Cada ação faz parte de um propósito maior.", study: "O Shemá é a declaração de fé central do judaísmo, recitada duas vezes ao dia. É a primeira oração ensinada às crianças e a última palavras de muitos judeus.", practice: "Ao acordar e antes de dormir, recite o Shemá com intenção. Comece e termine o dia reconhecendo a unidade de Deus." },
    { verse: "Não é a ti que cabe completar a obra, mas também não és livre para desistir dela.", source: "Pirkei Avot 2:16 (Rabi Tarfon)", reflection: "A perfeição não é exigida, mas a persistência sim. Continue caminhando, mesmo em passos pequenos.", study: "Pirkei Avot (Ética dos Pais) é um tratado do Talmud sobre ética. Rabi Tarfon ensina que nosso dever é o esforço, não o resultado — o resultado pertence a Deus.", practice: "Escolha uma mitsvá (boa ação) prática para hoje. Não se preocupe em fazer perfeitamente — comece." },
    { verse: "Tzedek, tzedek tirdof — Justiça, justiça perseguirás.", source: "Deuteronômio 16:20", reflection: "A repetição da palavra 'justiça' enfatiza: busque-a de forma justa. Os fins não justificam os meios.", study: "A tzedaká (justiça/caridade) é um pilar do judaísmo. Maimonides classificou 8 níveis de caridade, sendo o mais alto ajudar alguém a se tornar autossuficiente.", practice: "Pratique tzedaká hoje: doe tempo, recursos ou conhecimento. Faça-o de forma que dignifique quem recebe." },
    { verse: "Se eu não sou por mim, quem será? Se sou somente por mim, que sou eu? Se não agora, quando?", source: "Pirkei Avot 1:14 (Hilel)", reflection: "Hilel nos ensina o equilíbrio entre autocuidado, altruísmo e urgência na ação.", study: "Hilel foi um dos maiores sábios do judaísmo. Esta tripla pergunta encapsula a ética judaica: responsabilidade pessoal, responsabilidade social e ação imediata.", practice: "Responda cada pergunta para sua situação atual. O que você precisa fazer por si? Pelos outros? E quando vai começar?" },
    { verse: "Tikkun Olam — Reparar o mundo.", source: "Conceito central da Mishná", reflection: "Cada ação de bondade, justiça e reparo contribui para a restauração do mundo.", study: "Tikkun Olam é o conceito judaico de que os seres humanos são parceiros de Deus na melhoria do mundo. Cada mitsvá cumprida ajuda a 'consertar' um aspecto da criação.", practice: "Identifique algo 'quebrado' ao seu redor — um relacionamento, uma injustiça, um problema ambiental. Tome uma ação concreta para repará-lo." },
    { verse: "Quem salva uma vida, salva o mundo inteiro.", source: "Talmud, Sanhedrin 37a", reflection: "Cada pessoa é um mundo completo. Ajudar uma pessoa é um ato cósmico.", study: "O Talmud ensina que cada ser humano é único e insubstituível. Por isso, destruir uma vida é destruir um mundo, e salvar uma vida é salvar um mundo.", practice: "Esteja atento hoje a alguém que precisa de ajuda — uma palavra de encorajamento, um favor, uma presença solidária. Você pode salvar um mundo." },
    { verse: "Gam zu l'tovah — Isso também é para o bem.", source: "Talmud, Taanit 21a (Nachum Ish Gamzu)", reflection: "A fé judaica ensina que mesmo o aparentemente negativo serve a um propósito divino.", study: "Nachum Ish Gamzu dizia 'Isso também é para o bem' diante de toda adversidade. Sua fé inabalável se tornou modelo de confiança em Deus.", practice: "Diante de uma dificuldade hoje, diga: 'Gam zu l'tovah.' Confie que Deus está trabalhando mesmo no que você não entende." },
  ],
  hinduista: [
    { verse: "Você tem direito à ação, mas nunca aos frutos da ação.", source: "Bhagavad Gita 2:47", reflection: "Faça o que é certo sem apego ao resultado. A ação desinteressada liberta a alma.", study: "Krishna ensina Arjuna sobre karma yoga — o caminho da ação desapegada. Agir sem apego ao resultado é a chave para a libertação (moksha).", practice: "Realize suas tarefas hoje com excelência, mas sem ansiedade pelo resultado. Foque no processo, não no prêmio." },
    { verse: "O Eu interior não nasce nem morre. Não tendo vindo a ser, não deixará de ser.", source: "Bhagavad Gita 2:20", reflection: "A alma (atman) é eterna. As mudanças do corpo e da vida são temporárias como roupas trocadas.", study: "O conceito de atman (alma eterna) é central no hinduísmo. A morte é apenas uma transição — como trocar de roupa. Isso dá perspectiva sobre as perdas da vida.", practice: "Reflita sobre o que é permanente em você versus o que é transitório. Cultive paz sabendo que sua essência é eterna." },
    { verse: "Quando a meditação é dominada, a mente é como a chama de uma vela em lugar sem vento.", source: "Bhagavad Gita 6:19", reflection: "Uma mente treinada pela meditação se torna estável e luminosa como uma chama protegida.", study: "O Gita descreve vários tipos de yoga (caminhos). Dhyana yoga (meditação) acalma a mente e revela o atman interior. A disciplina mental é fundamental.", practice: "Sente-se em silêncio por 10 minutos. Foque em um mantra (como 'Om') ou na respiração até sua mente se tornar como uma chama estável." },
    { verse: "Ahimsa paramo dharma — A não-violência é o dever supremo.", source: "Mahabharata", reflection: "A não-violência começa nos pensamentos, passa pelas palavras e se manifesta nas ações.", study: "Ahimsa é o princípio da não-violência que influenciou Gandhi e o mundo. No hinduísmo, abrange não causar dano a nenhum ser vivo — em pensamento, palavra ou ação.", practice: "Observe seus pensamentos hoje. Quando surgir julgamento ou agressividade, substitua por compaixão. Pratique ahimsa em cada interação." },
    { verse: "O universo inteiro está dentro de você. Pergunte tudo a si mesmo.", source: "Rumi (influência sufi-hindu)", reflection: "Todas as respostas que você busca já existem dentro de você. Olhe para dentro.", study: "A tradição védica ensina que o atman individual é idêntico ao Brahman universal. 'Tat tvam asi' (Tu és Isso) — o divino está dentro de cada ser.", practice: "Faça uma pergunta importante que está em seu coração. Medite sobre ela em silêncio por 10 minutos. Confie na resposta que surgir." },
    { verse: "Yoga é a jornada do eu, através do eu, para o eu.", source: "Bhagavad Gita 6:5", reflection: "O verdadeiro yoga não é apenas físico — é a união da alma individual com o divino.", study: "Yoga significa 'união'. No Gita, Krishna descreve quatro caminhos: karma yoga (ação), bhakti yoga (devoção), jnana yoga (conhecimento) e raja yoga (meditação).", practice: "Pratique alguma forma de yoga hoje — física, devocional ou meditativa. Busque a união entre corpo, mente e espírito." },
    { verse: "Om é o som primordial do universo, a sílaba sagrada.", source: "Mandukya Upanishad", reflection: "Om representa a totalidade da existência. Recitá-lo conecta você à vibração cósmica.", study: "Os Upanishads ensinam que Om contém toda a realidade — passado, presente e futuro. É o som que originou a criação e permeia tudo que existe.", practice: "Sente-se confortavelmente, feche os olhos e cante 'Om' 21 vezes. Sinta a vibração percorrer todo o seu corpo." },
  ],
  taoista: [
    { verse: "O Tao que pode ser expresso não é o Tao eterno.", source: "Tao Te Ching, capítulo 1 — Lao Tzu", reflection: "O mistério da vida não pode ser totalmente capturado em palavras. Viva o mistério, não tente explicá-lo.", study: "O Tao Te Ching é o texto fundamental do taoísmo. O primeiro verso já ensina humildade intelectual: a verdade última transcende a linguagem.", practice: "Passe alguns minutos em silêncio contemplativo. Não tente entender — apenas esteja presente no mistério da existência." },
    { verse: "A água é fluida, suave e sem resistência. Contudo, a água desgasta a rocha.", source: "Lao Tzu", reflection: "A suavidade persistente supera a força bruta. Seja como a água: adaptável mas constante.", study: "Wu wei (não-ação/ação sem esforço) é central no taoísmo. A água é o símbolo perfeito: não luta contra obstáculos, mas os contorna e, com o tempo, os vence.", practice: "Em situações de conflito hoje, escolha a suavidade. Em vez de forçar, flua ao redor do obstáculo." },
    { verse: "A jornada de mil milhas começa com um único passo.", source: "Tao Te Ching, capítulo 64", reflection: "Não se assuste com a grandeza do objetivo. O poder está no passo dado agora.", study: "Lao Tzu ensina que grandes realizações são compostas de pequenos atos. O taoísmo valoriza a simplicidade e a paciência como virtudes fundamentais.", practice: "Identifique um grande objetivo que parece distante. Dê um único passo concreto em sua direção hoje." },
    { verse: "Quando eu me solto do que sou, me torno o que poderia ser.", source: "Lao Tzu", reflection: "O apego à identidade fixa limita o crescimento. Soltar-se é abrir espaço para a transformação.", study: "O taoísmo ensina que a rigidez é morte e a flexibilidade é vida. Assim como o bambu sobrevive ao vendaval por ser flexível, nós crescemos quando nos permitimos mudar.", practice: "Identifique uma crença rígida sobre si mesma. Pergunte: 'E se eu pudesse ser diferente?' Permita-se experimentar uma nova forma de ser." },
    { verse: "O sábio age sem esforço e ensina sem palavras.", source: "Tao Te Ching, capítulo 2", reflection: "As maiores lições são transmitidas pelo exemplo, não pelo discurso.", study: "Wu wei é agir em harmonia com o fluxo natural das coisas. Não é inação, mas ação alinhada, como um rio que não precisa se esforçar para correr.", practice: "Hoje, em vez de dar conselhos, dê o exemplo. Ensine pelo que você faz, não pelo que diz." },
    { verse: "Simplicidade, paciência, compaixão. Estes três são seus maiores tesouros.", source: "Tao Te Ching, capítulo 67", reflection: "As virtudes mais profundas são também as mais simples. Cultive-as diariamente.", study: "Lao Tzu identifica três tesouros: ci (compaixão), jian (frugalidade/simplicidade) e bu gan wei tianxia xian (humildade). São a base da vida taoísta.", practice: "Pratique simplicidade em uma área da vida hoje: simplifique uma refeição, uma decisão ou um pensamento." },
    { verse: "Aquele que conhece os outros é sábio; aquele que conhece a si mesmo é iluminado.", source: "Tao Te Ching, capítulo 33", reflection: "O autoconhecimento é superior ao conhecimento do mundo. A sabedoria verdadeira olha para dentro.", study: "No taoísmo, a iluminação não vem de acumular conhecimento externo, mas de compreender a própria natureza e sua relação com o Tao.", practice: "Passe 10 minutos em auto-observação silenciosa. Observe seus pensamentos sem julgá-los." },
  ],
  xintoista: [
    { verse: "Até mesmo o mais pequeno santuário pode abrigar um grande kami.", source: "Provérbio Xintoísta", reflection: "O sagrado não depende de grandeza externa. O divino habita em toda a criação.", study: "O xintoísmo acredita que kami (espíritos/divindades) habitam em toda a natureza — árvores, rios, montanhas. Até o menor espaço pode ser sagrado.", practice: "Visite um espaço natural hoje — um parque, jardim ou árvore. Reconheça a presença sagrada na natureza ao seu redor." },
    { verse: "A sinceridade do coração (makoto) é o caminho dos kami.", source: "Ensinamento Xintoísta", reflection: "A pureza de intenção é mais importante que rituais elaborados. Seja sincera em tudo.", study: "Makoto (sinceridade/verdade) é uma das virtudes centrais do xintoísmo. Os kami respondem à sinceridade do coração, não à perfeição dos rituais.", practice: "Em todas as suas interações hoje, pratique makoto: seja genuína, honesta e sincera. Alinhe palavras e intenções." },
    { verse: "Purifica-te como a água que corre, e os kami estarão contigo.", source: "Tradição Xintoísta — Misogi", reflection: "A purificação não é apenas física — é mental e espiritual. Deixe fluir o que não serve mais.", study: "Misogi (purificação pela água) é uma prática xintoísta ancestral. A água corrente simboliza a renovação constante e a remoção de impurezas espirituais.", practice: "Tome um banho consciente: enquanto a água corre, visualize-a levando embora preocupações e negatividade." },
    { verse: "Trate a natureza com respeito, pois ela é morada dos kami.", source: "Princípio Xintoísta", reflection: "A natureza não é recurso a ser explorado, mas santuário a ser reverenciado.", study: "O xintoísmo é profundamente ecológico. Cada elemento natural pode abrigar kami. Os torii (portões vermelhos) marcam a entrada de espaços sagrados na natureza.", practice: "Faça algo pela natureza hoje: cuide de uma planta, recolha um lixo, contemple uma paisagem com gratidão." },
    { verse: "O que importa não é a prece, mas o coração que ora.", source: "Sabedoria Xintoísta", reflection: "Rituais sem coração são vazios. A verdadeira espiritualidade está na intenção.", study: "No xintoísmo, a oração (norito) nos santuários é feita com batidas de palmas para atrair a atenção dos kami. Mas é a pureza do coração que determina a resposta.", practice: "Ore hoje com total presença. Bata duas palmas, incline-se e faça seu pedido com sinceridade absoluta." },
    { verse: "Harmonia (wa) é o princípio supremo.", source: "Princípio Xintoísta", reflection: "A busca pela harmonia — consigo, com os outros e com a natureza — é o ideal mais elevado.", study: "Wa (harmonia) permeia toda a cultura japonesa influenciada pelo xintoísmo. Manter a harmonia social e interior é considerado virtude suprema.", practice: "Identifique uma área de dissonância em sua vida. Tome uma ação para restaurar a harmonia — uma conversa, um perdão, uma mudança." },
    { verse: "Cada dia é um novo nascimento, cada amanhecer um novo começo.", source: "Tradição Xintoísta", reflection: "O xintoísmo celebra a renovação constante. Cada dia é uma oportunidade de recomeçar.", study: "Os rituais xintoístas de purificação (harae) representam a renovação constante. Assim como a natureza se renova a cada estação, cada dia é um novo início.", practice: "Ao acordar, reconheça: hoje é um novo começo. Que erros de ontem não determinem as escolhas de hoje." },
  ],
  sikh: [
    { verse: "Há apenas um Deus. Seu nome é Verdade. Ele é o Criador.", source: "Mul Mantar — Guru Granth Sahib", reflection: "A unidade de Deus e a verdade como Seu nome nos convida a viver com integridade.", study: "O Mul Mantar é a oração de abertura do Guru Granth Sahib, escritura sagrada do sikhismo. Resume toda a teologia sikh em poucas palavras.", practice: "Comece o dia recitando: 'Ik Onkar, Sat Nam' (Um Deus, Seu nome é Verdade). Viva com verdade e integridade hoje." },
    { verse: "Antes que os oceanos e a terra existissem, apenas a Ordem do Criador prevalecia.", source: "Guru Nanak — Japji Sahib", reflection: "Existe uma ordem divina (Hukam) que governa tudo. Aceitar Hukam traz paz interior.", study: "Guru Nanak, fundador do sikhismo, ensinou que aceitar a vontade divina (Hukam) é o caminho para a paz. Não é resignação passiva, mas aceitação ativa e confiante.", practice: "Identifique algo em sua vida que está fora do seu controle. Aceite-o como Hukam e foque sua energia no que pode mudar." },
    { verse: "O que você semeia, você colherá. Este corpo é o resultado de suas ações.", source: "Guru Granth Sahib, p. 134", reflection: "Cada ação gera consequências. Plante bondade e colherá paz.", study: "O sikhismo acredita em karma e reencarnação. As ações desta vida determinam as condições da próxima. A meditação no Nome de Deus (Naam Simran) purifica o karma.", practice: "Faça uma lista de 'sementes' que você quer plantar: atos de bondade, disciplina, estudo. Plante pelo menos uma hoje." },
    { verse: "Reconheça toda a raça humana como uma só.", source: "Guru Gobind Singh", reflection: "Não há distinção de casta, raça ou gênero diante de Deus. Todos são iguais.", study: "O sikhismo é radical em sua igualdade: os Gurdwaras (templos) servem langar (refeição gratuita) a todos sem distinção. Esta prática data do tempo de Guru Nanak.", practice: "Trate cada pessoa que encontrar hoje com igual respeito e dignidade, independente de sua posição social." },
    { verse: "Medite no Nome do Senhor e todos os seus assuntos serão resolvidos.", source: "Guru Arjan Dev — Sukhmani Sahib", reflection: "A meditação no Nome de Deus (Naam) é a solução para todos os problemas da vida.", study: "Naam Simran (meditação no Nome divino) é a prática central do sikhismo. Repetir 'Waheguru' (Maravilhoso Mestre) conecta a alma ao Criador.", practice: "Sente-se em silêncio e repita 'Waheguru' por 10 minutos. Deixe o som preencher sua mente e acalmar seu coração." },
    { verse: "Aquele que serve os outros encontra a Deus.", source: "Guru Granth Sahib", reflection: "Seva (serviço desinteressado) é o caminho mais direto para Deus no sikhismo.", study: "Seva é um dos três pilares do sikhismo (junto com Naam Japna e Kirat Karni). Servir sem esperar recompensa é uma forma de adoração.", practice: "Faça um ato de serviço desinteressado hoje: ajude alguém sem esperar nada em troca." },
    { verse: "Com a bênção do Guru, a escuridão da ignorância é dissipada.", source: "Guru Granth Sahib", reflection: "O Guru (mestre espiritual) ilumina o caminho. No sikhismo, o Guru Granth Sahib é o Guru eterno.", study: "Após os dez Gurus humanos, o Guru Granth Sahib foi declarado Guru eterno dos Sikhs. Sua leitura e contemplação guiam os fiéis.", practice: "Leia uma passagem do Guru Granth Sahib ou reflita sobre os ensinamentos de um dos dez Gurus. Deixe a sabedoria iluminar seu dia." },
  ],
  umbanda: [
    { verse: "A Umbanda é a manifestação do espírito para a prática da caridade.", source: "Caboclo das Sete Encruzilhadas — 1908", reflection: "A caridade é a essência da Umbanda. Servir aos outros é servir ao divino.", study: "A Umbanda foi fundada em 1908 no Rio de Janeiro. Combina elementos indígenas, africanos, católicos e espíritas. A caridade é seu princípio norteador.", practice: "Pratique a caridade de forma concreta hoje: ajude alguém em necessidade, ofereça palavras de conforto ou doe algo que não usa mais." },
    { verse: "Salve a força que vem da mata! Salve a força que vem do mar!", source: "Ponto cantado de Umbanda", reflection: "A natureza é sagrada e fonte de força espiritual. As forças da mata e do mar renovam e curam.", study: "Na Umbanda, os Orixás se manifestam através das forças da natureza. Oxóssi governa as matas, Iemanjá governa o mar. Cada elemento natural tem significado espiritual.", practice: "Conecte-se com a natureza hoje: visite uma área verde, ouça o som da água ou simplesmente contemple o céu." },
    { verse: "Quem tem fé não tropeça, quem tem Deus não fraqueja.", source: "Ensinamento de Preto Velho", reflection: "A fé e a conexão com o divino são as bases da força espiritual.", study: "Os Pretos Velhos são espíritos de escravizados que alcançaram grande evolução. Sua sabedoria, paciência e amor são pilares da Umbanda.", practice: "Acenda uma vela branca e faça uma prece simples pedindo fé e proteção. Confie que os guias espirituais estão ao seu lado." },
    { verse: "Cada um no seu caminho, todos em direção à luz.", source: "Sabedoria Umbandista", reflection: "Não existe um único caminho espiritual. A Umbanda respeita todas as religiões e caminhos.", study: "A Umbanda é sincrética e inclusiva por natureza. Reconhece que todos os caminhos sinceros levam ao mesmo destino: a evolução espiritual e o encontro com Deus.", practice: "Respeite o caminho espiritual de outra pessoa hoje. Aprenda algo sobre uma tradição diferente da sua." },
    { verse: "A gira é o encontro do céu com a terra.", source: "Tradição Umbandista", reflection: "Nos rituais umbandistas, o mundo espiritual se encontra com o material para curar e orientar.", study: "A gira é o ritual central da Umbanda, onde as entidades se manifestam através dos médiuns para oferecer orientação, cura e caridade espiritual.", practice: "Reserve um momento de silêncio e oração. Peça orientação aos seus guias espirituais. Esteja aberta para receber sinais ao longo do dia." },
    { verse: "Oxalá nos dê paz e amor para seguir em frente.", source: "Ponto cantado de Oxalá", reflection: "Oxalá, o orixá da paz e da criação, nos lembra que paz e amor são forças de transformação.", study: "Oxalá é o orixá supremo na Umbanda, sincretizado com Jesus Cristo. Representa a paz, a fé e a criação. Sua cor é o branco, símbolo de pureza.", practice: "Vista-se de branco ou use um acessório branco hoje. Cultive paz interior e espalhe amor por onde passar." },
    { verse: "Na Umbanda não se cobra, se dá. Não se julga, se acolhe.", source: "Princípio Umbandista", reflection: "A gratuidade e o acolhimento são marcas da verdadeira espiritualidade.", study: "A Umbanda genuína não cobra por atendimentos espirituais. A caridade material e espiritual deve ser gratuita, seguindo o princípio: 'De graça recebestes, de graça dai.'", practice: "Ofereça algo de graça hoje: seu tempo, sua escuta, sua ajuda. Sem esperar nada em troca." },
  ],
  candomble: [
    { verse: "Axé! A força vital que move o universo está em tudo e em todos.", source: "Tradição Yorubá", reflection: "Axé é a energia sagrada que permeia toda a criação. Você carrega essa força dentro de si.", study: "Axé é o conceito central do Candomblé — a força vital divina presente em tudo. Os rituais, oferendas e cantos servem para fortalecer e direcionar essa energia.", practice: "Reconheça o axé em tudo ao seu redor hoje: na comida, nas pessoas, na natureza. Diga 'Axé!' como afirmação de força." },
    { verse: "Cada pessoa tem seu Orixá, cada cabeça tem seu ori.", source: "Sabedoria do Candomblé", reflection: "Seu ori (cabeça/destino) é sagrado e único. Honre seu caminho individual.", study: "No Candomblé, ori é a essência individual, a cabeça interior que guia o destino. O borí (ritual de alimentar a cabeça) fortalece o ori e alinha com o Orixá.", practice: "Cuide da sua 'cabeça' hoje: alimente-se bem, pense positivo, proteja seus pensamentos. Seu ori é sagrado." },
    { verse: "Sem folha não há Orixá. A natureza é o templo sagrado.", source: "Ossaim — Orixá das folhas", reflection: "A natureza é fonte de cura e conexão espiritual. Sem ela, não há religião.", study: "Ossaim é o Orixá das folhas medicinais e litúrgicas. No Candomblé, as folhas são essenciais para todos os rituais. A relação com a natureza é sagrada.", practice: "Cuide de uma planta hoje. Se não tiver, comece a cultivar uma. Reconheça a força espiritual presente no mundo vegetal." },
    { verse: "O tambor fala a língua dos Orixás.", source: "Tradição do Candomblé", reflection: "A música e o ritmo são formas sagradas de comunicação com o divino.", study: "Os atabaques (tambores sagrados) são consagrados e tratados como seres sagrados no Candomblé. Cada toque corresponde a um Orixá e tem poder de invocação.", practice: "Ouça músicas de tambores ou cânticos dos Orixás. Deixe o ritmo tocar seu coração e renovar sua energia." },
    { verse: "Respeite os mais velhos, pois neles está a sabedoria ancestral.", source: "Princípio do Candomblé", reflection: "A ancestralidade e a hierarquia espiritual são fontes de sabedoria e proteção.", study: "No Candomblé, a senioridade é profundamente respeitada. Os mais velhos (egbomi) guardam conhecimentos transmitidos oralmente por gerações. A tradição oral é sagrada.", practice: "Honre uma pessoa mais velha hoje: peça um conselho, ouça uma história, demonstre respeito e gratidão pela sabedoria que carregam." },
    { verse: "Exu não é o diabo. Exu é o mensageiro, o guardião dos caminhos.", source: "Tradição Yorubá", reflection: "Exu abre caminhos e possibilidades. Sem ele, nenhuma comunicação com o sagrado é possível.", study: "Exu/Eshu é o Orixá da comunicação, das encruzilhadas e do movimento. No Candomblé, é saudado primeiro em qualquer ritual, pois é o mensageiro entre humanos e Orixás.", practice: "Ao iniciar qualquer empreendimento hoje, peça a abertura de caminhos. Reconheça que todo começo precisa de uma porta aberta." },
    { verse: "Oferenda não é troca, é gratidão. Não se compra o sagrado.", source: "Princípio do Candomblé", reflection: "A relação com o divino não é transacional. Oferendas são expressões de gratidão e respeito.", study: "As oferendas (ebós) no Candomblé são atos de devoção e equilíbrio energético. Cada Orixá tem preferências alimentares e elementos que representam sua energia.", practice: "Ofereça algo simbólico hoje: um copo d'água, uma fruta, uma flor. Faça-o com gratidão sincera, sem pedir nada em troca." },
  ],
  wicca: [
    { verse: "Faça o que quiser, desde que não prejudique ninguém.", source: "Rede Wicca (Wiccan Rede)", reflection: "A liberdade vem com responsabilidade. Sua magia e suas ações devem respeitar todos os seres.", study: "A Rede Wicca é o princípio ético fundamental da Wicca. 'An it harm none, do what ye will' ensina que a liberdade pessoal termina onde começa o dano ao outro.", practice: "Antes de cada decisão hoje, pergunte: 'Isso prejudica alguém?' Se não, siga em frente com confiança." },
    { verse: "Assim como acima, assim é abaixo. Assim como dentro, assim é fora.", source: "Princípio Hermético adotado pela Wicca", reflection: "O microcosmo reflete o macrocosmo. Sua realidade interior cria sua realidade exterior.", study: "Este princípio hermético é central na prática wiccana. A magia funciona porque o universo é interconectado — mudanças internas criam mudanças externas.", practice: "Observe sua realidade exterior como espelho da interior. Se algo não vai bem fora, olhe para dentro. Que mudança interna criaria a mudança desejada?" },
    { verse: "A Deusa está em tudo e em todos. Ela é a Terra, a Lua e as estrelas.", source: "Tradição Wicca", reflection: "O feminino divino está presente em toda a criação. Honre a Deusa em você e na natureza.", study: "A Wicca venera a Deusa (feminino) e o Deus (masculino) como aspectos complementares do divino. A Deusa se manifesta nas fases da lua: crescente (donzela), cheia (mãe), minguante (anciã).", practice: "Observe a fase da lua hoje. Alinhe sua energia: lua crescente para começar projetos, cheia para celebrar, minguante para soltar, nova para descansar." },
    { verse: "O que você envia retorna três vezes.", source: "Lei Tríplice da Wicca", reflection: "Toda energia que você emite — positiva ou negativa — retorna multiplicada por três.", study: "A Lei Tríplice ensina consequência kármica amplificada. É um lembrete poderoso para usar a energia (magia) com responsabilidade e boas intenções.", practice: "Envie energia positiva hoje: bênçãos, bons desejos, pensamentos de cura. Saiba que voltarão triplicados para você." },
    { verse: "Na Roda do Ano, cada estação é sagrada.", source: "Tradição Wicca — Sabbats", reflection: "Cada fase da vida — nascimento, crescimento, colheita, repouso — tem seu propósito e beleza.", study: "A Wicca celebra 8 sabbats (festivais sazonais) que marcam a Roda do Ano: Samhain, Yule, Imbolc, Ostara, Beltane, Litha, Lughnasadh e Mabon.", practice: "Identifique em qual 'estação' da vida você está: plantando, crescendo, colhendo ou descansando? Honre essa fase." },
    { verse: "A magia é a arte de mudar a consciência de acordo com a vontade.", source: "Dion Fortune", reflection: "Magia não é sobrenatural — é a habilidade natural de transformar a realidade através da intenção focada.", study: "Na Wicca, magia é prática e intencional. Envolve rituais, visualizações, ervas e cristais como ferramentas para focar a intenção e manifestar mudanças.", practice: "Acenda uma vela e faça uma intenção clara para o dia. Visualize o resultado desejado. Deixe a vela queimar enquanto trabalha em direção ao objetivo." },
    { verse: "Abençoada seja esta terra, abençoadas sejam todas as criaturas.", source: "Bênção Wicca", reflection: "A Wicca honra toda a vida. A Terra é sagrada e todas as criaturas merecem respeito.", study: "A Wicca é uma religião da natureza. A Terra (Gaia) é vista como a Grande Mãe. O respeito ambiental não é político — é espiritual.", practice: "Conecte-se com a Terra hoje: ande descalça na grama, abrace uma árvore, agradeça pela comida que a Terra provê." },
  ],
  bahai: [
    { verse: "A Terra é um só país e a humanidade seus cidadãos.", source: "Bahá'u'lláh", reflection: "Não existem fronteiras no espírito. Toda a humanidade é uma única família.", study: "A unidade da humanidade é o princípio central da Fé Bahá'í. Bahá'u'lláh ensinou que preconceitos de raça, nação e religião devem ser superados.", practice: "Trate cada pessoa que encontrar hoje como membro da sua família humana. Transcenda qualquer preconceito." },
    { verse: "A religião deve ser causa de amor e unidade. Se se torna causa de desunião, é melhor não ter religião.", source: "'Abdu'l-Bahá", reflection: "A verdadeira espiritualidade une as pessoas. Se sua fé separa, algo precisa mudar.", study: "'Abdu'l-Bahá, filho de Bahá'u'lláh, ensinou que todas as religiões vêm do mesmo Deus e que seus ensinamentos essenciais são os mesmos.", practice: "Encontre um ponto de concordância com alguém de religião diferente. Celebre o que une em vez de focar no que separa." },
    { verse: "Sê generoso na prosperidade e grato na adversidade.", source: "Bahá'u'lláh", reflection: "A verdadeira nobreza de caráter se mostra tanto na abundância quanto na escassez.", study: "Bahá'u'lláh deixou extensas escrituras sobre virtudes práticas. A generosidade e a gratidão são pilares do caráter bahá'í.", practice: "Se está em momento bom, seja generosa com alguém. Se está em momento difícil, encontre algo pelo qual ser grata." },
    { verse: "A educação é a mais poderosa arma que você pode usar para mudar o mundo.", source: "Princípio Bahá'í", reflection: "A educação universal — especialmente das meninas — é chave para a transformação social.", study: "A Fé Bahá'í enfatiza a educação universal obrigatória. Se os recursos são limitados, a educação das meninas deve ter prioridade, pois as mães educam as futuras gerações.", practice: "Aprenda algo novo hoje. Depois, ensine algo a alguém. O conhecimento cresce quando compartilhado." },
    { verse: "O trabalho realizado em espírito de serviço é a mais alta forma de adoração.", source: "Bahá'u'lláh", reflection: "Trabalhar com dedicação e servir aos outros é tão sagrado quanto orar.", study: "Na Fé Bahá'í, não há monasticismo. O trabalho é adoração. Servir à humanidade através da profissão é uma forma de oração prática.", practice: "Realize seu trabalho hoje com espírito de serviço. Veja cada tarefa como uma oferenda ao bem comum." },
    { verse: "Deixa que tua visão alcance o mundo, não te limites a ti mesmo.", source: "Bahá'u'lláh", reflection: "Pensar além de si mesmo é o primeiro passo para a verdadeira grandeza espiritual.", study: "Bahá'u'lláh convida seus seguidores a pensar globalmente. O patriotismo limitado deve dar lugar ao amor pela humanidade inteira.", practice: "Amplie sua perspectiva hoje: leia sobre uma cultura diferente, ore por um país em crise, pense em como suas ações afetam o todo." },
    { verse: "Consultem entre si, pois a consulta é a lâmpada da orientação.", source: "Bahá'u'lláh", reflection: "Decisões tomadas em grupo, com respeito mútuo, são mais sábias que decisões solitárias.", study: "A consulta bahá'í é um processo de tomada de decisão coletiva baseado no respeito, na escuta e na busca da verdade. Não há debates — há construção conjunta.", practice: "Antes de tomar uma decisão importante, consulte alguém de confiança. Ouça com abertura e considere perspectivas diferentes." },
  ],
  confucionista: [
    { verse: "Não faças aos outros o que não queres que te façam.", source: "Confúcio — Analectos 15:24", reflection: "A Regra de Ouro é universal. A empatia ativa é a base de toda moralidade.", study: "Confúcio formulou esta versão negativa da Regra de Ouro 500 anos antes de Cristo. O conceito de 'ren' (benevolência) é o coração de toda a ética confucionista.", practice: "Antes de agir ou falar, pergunte: 'Eu gostaria que fizessem isso comigo?' Se não, mude de abordagem." },
    { verse: "Aprender sem refletir é inútil. Refletir sem aprender é perigoso.", source: "Confúcio — Analectos 2:15", reflection: "Conhecimento sem reflexão é superficial. Reflexão sem estudo é especulação vazia.", study: "Confúcio valorizava igualmente o estudo (xue) e a reflexão (si). A educação confucionista busca formar pessoas de caráter, não apenas acumular informação.", practice: "Após ler ou estudar algo hoje, pare e reflita: 'O que isso significa para minha vida? Como posso aplicar isso?'" },
    { verse: "A jornada de mil li começa sob seus pés.", source: "Confúcio", reflection: "Grandes realizações começam com o primeiro passo. Não espere condições perfeitas para começar.", study: "O confucionismo valoriza a ação prática e gradual. O junzi (pessoa exemplar) não adia o que precisa ser feito.", practice: "Identifique algo que você tem adiado. Dê o primeiro passo hoje, por menor que seja." },
    { verse: "O homem superior busca o que é certo; o homem inferior busca o que é lucrativo.", source: "Confúcio — Analectos 4:16", reflection: "A verdadeira nobreza está em buscar a retidão, não o lucro pessoal.", study: "O junzi (pessoa exemplar) é o ideal confucionista: alguém que prioriza yi (retidão) sobre li (lucro). Caráter vale mais que riqueza.", practice: "Em cada decisão hoje, pergunte: 'Isso é o certo a fazer?' antes de perguntar 'Isso me beneficia?'" },
    { verse: "Quando vires um homem de valor, busca igualar-te a ele. Quando vires um homem sem valor, examina-te interiormente.", source: "Confúcio — Analectos 4:17", reflection: "Os outros são nossos espelhos: inspire-se nos virtuosos e aprenda com os exemplos negativos.", study: "O autoexame constante é uma prática confucionista. Zengzi, discípulo de Confúcio, dizia: 'Três vezes ao dia examino minha conduta.'", practice: "Identifique alguém que você admira. Que virtude dessa pessoa você pode cultivar hoje? Identifique também algo em outros que te incomoda — isso reflete algo em você?" },
    { verse: "A piedade filial (xiao) é a raiz de toda virtude.", source: "Livro da Piedade Filial (Xiaojing)", reflection: "O respeito e cuidado pelos pais e ancestrais é a base de todas as outras virtudes.", study: "Xiao (piedade filial) é o valor fundamental do confucionismo. Honrar os pais, cuidar dos idosos e respeitar os ancestrais são deveres sagrados.", practice: "Demonstre amor e gratidão a seus pais ou figuras parentais hoje. Uma ligação, uma visita ou uma lembrança sincera." },
    { verse: "Se você quer mudar o mundo, comece por se aperfeiçoar.", source: "Confúcio — Grande Aprendizado", reflection: "A mudança social começa com a transformação pessoal. Aperfeiçoe-se primeiro.", study: "O Grande Aprendizado descreve a sequência: cultivar-se → harmonizar a família → governar o estado → pacificar o mundo. Tudo começa com o auto-cultivo.", practice: "Identifique uma área de auto-aperfeiçoamento. Dedique tempo hoje a melhorá-la: leitura, prática, disciplina." },
  ],
  jainista: [
    { verse: "Ahimsa Paramo Dharma — A não-violência é a religião suprema.", source: "Princípio Central do Jainismo", reflection: "A não-violência absoluta — em pensamento, palavra e ação — é o ideal mais elevado.", study: "O jainismo pratica ahimsa de forma mais rigorosa que qualquer outra tradição. Monges jainistas usam pano sobre a boca para não inalar insetos e varrem o chão ao caminhar.", practice: "Pratique não-violência completa hoje: não mate insetos, não fale mal de ninguém, não tenha pensamentos agressivos." },
    { verse: "Todas as almas são potencialmente divinas. O objetivo é manifestar essa divindade.", source: "Ensinamento Jainista", reflection: "Cada ser vivo tem uma alma (jiva) com potencial infinito. Reconheça a divindade em todos.", study: "O jainismo ensina que cada jiva (alma) tem conhecimento, percepção e felicidade infinitos — obscurecidos apenas pelo karma acumulado. A liberação (moksha) revela essa natureza.", practice: "Olhe para cada ser vivo hoje — pessoas, animais, plantas — e reconheça a alma divina em cada um." },
    { verse: "A verdade (satya) tem muitas faces. Nenhuma perspectiva sozinha a contém por completo.", source: "Anekantavada — Doutrina Jainista", reflection: "A realidade é multifacetada. Humildade intelectual é reconhecer que sua perspectiva é parcial.", study: "Anekantavada (muitos lados da verdade) é a contribuição filosófica única do jainismo. A parábola dos cegos e o elefante ilustra que cada um percebe parte da verdade.", practice: "Em um desacordo hoje, considere genuinamente a perspectiva do outro. Talvez ambos estejam certos de ângulos diferentes." },
    { verse: "O apego é a causa raiz do sofrimento.", source: "Ensinamento de Mahavira", reflection: "Quanto menos apego material e emocional, mais liberdade interior.", study: "Mahavira, o 24º Tirthankara, renunciou a tudo para alcançar a liberação. O aparigraha (não-possessividade) é um dos cinco votos fundamentais do jainismo.", practice: "Desapegue de algo material hoje: doe algo que não usa. Desapegue de algo emocional: solte uma expectativa rígida." },
    { verse: "O jejum purifica o corpo e disciplina a mente.", source: "Prática Jainista de Tapas", reflection: "A autodisciplina e a austeridade são caminhos para a purificação espiritual.", study: "O jainismo pratica vários tipos de jejum (tapas) como ferramenta espiritual. Não é punição, mas disciplina voluntária para fortalecer a alma.", practice: "Pratique alguma forma de disciplina hoje: jejum alimentar leve, silêncio por uma hora, ou renúncia a uma indulgência." },
    { verse: "Perdoe e peça perdão. A raiva acorrenta, o perdão liberta.", source: "Micchami Dukkadam — Prática Jainista", reflection: "O perdão mútuo é essencial para a libertação espiritual.", study: "No festival de Paryushana, os jainistas pedem perdão a todos com a frase 'Micchami Dukkadam' (que toda ofensa minha seja perdoada). O perdão é prática central.", practice: "Peça perdão a alguém que você magoou. Perdoe alguém que te magoou. Liberte-se das correntes da mágoa." },
    { verse: "Cada alma é arquiteta do seu próprio destino.", source: "Mahavira", reflection: "Você é responsável por seu próprio karma. Ninguém pode salvá-la senão você mesma.", study: "O jainismo não tem um deus criador. Cada alma é responsável por sua evolução. Os Tirthankaras são exemplos, não salvadores.", practice: "Assuma responsabilidade total por sua vida hoje. Não culpe circunstâncias — faça escolhas conscientes." },
  ],
  zoroastrista: [
    { verse: "Bons pensamentos, boas palavras, boas ações.", source: "Humata, Hukhta, Hvarshta — Avesta", reflection: "A tríade zoroastrista resume toda a ética: pense bem, fale bem, aja bem.", study: "O zoroastrismo, fundado por Zaratustra na Pérsia antiga, é uma das religiões mais antigas do mundo. Sua ética tríplice influenciou judaísmo, cristianismo e islã.", practice: "Monitore seus pensamentos, palavras e ações hoje. Antes de cada um, pergunte: 'Isso é bom?' Alinhe os três." },
    { verse: "A felicidade pertence àquele que traz felicidade aos outros.", source: "Zaratustra — Gathas", reflection: "A verdadeira felicidade não é egoísta — ela se multiplica quando compartilhada.", study: "Os Gathas são os hinos compostos pelo próprio Zaratustra. Ensina que asha (verdade/retidão) e vohu manah (bom pensamento) são os caminhos para a felicidade.", practice: "Faça alguém sorrir hoje. Sua felicidade aumentará proporcionalmente." },
    { verse: "A verdade (Asha) é o melhor bem. A felicidade pertence àquele que é justo.", source: "Ashem Vohu — Oração Zoroastrista", reflection: "Viver em verdade e retidão é o caminho para a felicidade genuína.", study: "Asha é o conceito central do zoroastrismo — ordem cósmica, verdade e retidão. Opõe-se a druj (mentira/caos). Toda a vida é uma escolha entre asha e druj.", practice: "Seja completamente honesta hoje. Não minta, não exagere, não omita. Viva em asha." },
    { verse: "Cada pessoa deve escolher entre Asha (verdade) e Druj (mentira).", source: "Ensinamento de Zaratustra", reflection: "O livre-arbítrio é sagrado. A cada momento, você escolhe entre a verdade e a ilusão.", study: "Zaratustra foi pioneiro no conceito de livre-arbítrio religioso. Ahura Mazda (Deus) criou os humanos com capacidade de escolher entre bem e mal.", practice: "Em cada decisão hoje, pergunte: 'Estou escolhendo asha (verdade) ou druj (mentira)?' Escolha conscientemente a verdade." },
    { verse: "O fogo sagrado ilumina o caminho da retidão.", source: "Tradição Zoroastrista", reflection: "O fogo é símbolo da presença divina e da verdade. Mantenha sua chama interior acesa.", study: "Os templos do fogo zoroastristas mantêm chamas que ardem continuamente, algumas por mais de 1.000 anos. O fogo representa Ahura Mazda e a verdade.", practice: "Acenda uma vela ou contemple uma chama. Que ela represente sua conexão com a verdade e a retidão." },
    { verse: "Proteja a criação de Ahura Mazda: a terra, a água, o fogo e o ar.", source: "Ensinamento Zoroastrista", reflection: "A proteção ambiental é um dever sagrado no zoroastrismo desde a antiguidade.", study: "O zoroastrismo é talvez a primeira religião ecológica. Poluir a terra, a água ou o ar é pecado. Os zoroastristas praticam reciclagem há milhares de anos.", practice: "Faça algo pela natureza hoje: economize água, evite desperdício, cuide do ambiente ao seu redor." },
    { verse: "Que sejamos como o sol que dá luz a todos sem distinção.", source: "Inspiração Zoroastrista", reflection: "Assim como o sol ilumina igualmente todos os seres, devemos irradiar bondade sem distinção.", study: "O sol (Hvar Khshaeta) é reverenciado no zoroastrismo como símbolo de Ahura Mazda. Sua luz representa asha (verdade) dispersando druj (escuridão/mentira).", practice: "Irradie bondade a todos hoje — sem escolher quem merece. Seja como o sol: ilumine sem pedir nada em troca." },
  ],
  ateista: [
    { verse: "Vivemos em um universo extraordinário. Cabe a nós dar significado à nossa existência.", source: "Carl Sagan", reflection: "Sem divindades, a responsabilidade de dar sentido à vida é inteiramente nossa — e isso é libertador.", study: "O humanismo secular propõe que a ética pode ser fundamentada na razão, empatia e experiência humana, sem necessidade de revelação sobrenatural.", practice: "Reflita sobre o que dá significado à sua vida. Tome uma decisão hoje que reflita seus valores mais profundos." },
    { verse: "A felicidade não é algo pronto. Ela vem das suas próprias ações.", source: "Dalai Lama (citado em contexto secular)", reflection: "Você é a autora da sua felicidade. Cada ação consciente constrói o bem-estar.", study: "A psicologia positiva confirma cientificamente que a felicidade é 40% influenciada por ações intencionais — mais que genética (50%) ou circunstâncias (10%).", practice: "Escolha três ações intencionais para aumentar seu bem-estar hoje: exercício, gratidão, conexão social." },
    { verse: "A vida não examinada não vale a pena ser vivida.", source: "Sócrates", reflection: "Questionar, refletir e buscar compreensão é o que nos torna plenamente humanos.", study: "A filosofia socrática propõe o autoexame constante como base da vida ética. O método socrático — perguntar, questionar, dialogar — é uma ferramenta poderosa.", practice: "Examine uma crença sua que nunca questionou. Pergunte: 'Por que acredito nisso? É baseado em evidências?'" },
    { verse: "Somos todos feitos de matéria estelar.", source: "Carl Sagan — Cosmos", reflection: "Os átomos do seu corpo foram forjados no coração de estrelas. Você é literalmente parte do cosmos.", study: "A ciência revela que somos feitos dos mesmos elementos criados em supernovas bilhões de anos atrás. Essa perspectiva cósmica pode inspirar admiração e humildade.", practice: "Olhe para o céu noturno e reconheça sua conexão com o cosmos. Você é parte de algo imenso e maravilhoso." },
    { verse: "A razão é a maior ferramenta que a humanidade possui para compreender o mundo.", source: "Iluminismo", reflection: "O pensamento racional e o método científico são as melhores ferramentas para navegar a realidade.", study: "O Iluminismo do século XVIII estabeleceu a razão como guia principal. Pensadores como Voltaire, Hume e Kant moldaram a ética secular moderna.", practice: "Questione uma suposição comum hoje. Busque evidências antes de aceitar qualquer afirmação." },
    { verse: "Trate os outros como você gostaria de ser tratado.", source: "Regra de Ouro — versão secular", reflection: "A empatia é a base universal da ética, independente de religião.", study: "A Regra de Ouro aparece em praticamente todas as culturas e pode ser fundamentada puramente na empatia e na reciprocidade, sem necessidade de mandamento divino.", practice: "Em cada interação hoje, coloque-se no lugar da outra pessoa antes de agir ou falar." },
    { verse: "O importante não é o que a vida faz com você, mas o que você faz com o que a vida faz com você.", source: "Jean-Paul Sartre (adaptado)", reflection: "O existencialismo ensina que somos livres para escolher como responder às circunstâncias.", study: "Sartre e o existencialismo propõem que 'a existência precede a essência' — não nascemos com um propósito pré-definido; criamos nosso próprio significado.", practice: "Diante de uma situação difícil, lembre-se: você não controla o que acontece, mas controla sua resposta. Escolha conscientemente." },
  ],
  agnostica: [
    { verse: "A única sabedoria verdadeira é saber que nada sabemos.", source: "Sócrates", reflection: "A humildade intelectual é o início da sabedoria. Reconhecer a incerteza é corajoso.", study: "O agnosticismo reconhece os limites do conhecimento humano sobre o divino. Não nega nem afirma — mantém a mente aberta para a possibilidade.", practice: "Abrace a incerteza hoje. Em vez de buscar respostas definitivas, aprecie as perguntas. A busca é tão valiosa quanto a resposta." },
    { verse: "Seja a mudança que você deseja ver no mundo.", source: "Mahatma Gandhi", reflection: "Independente de suas crenças sobre Deus, você pode ser agente de transformação positiva.", study: "O agnosticismo prático foca no que podemos fazer, não no que não podemos saber. A ação ética independe de certeza metafísica.", practice: "Identifique uma mudança que você quer ver ao redor e comece por si mesma." },
    { verse: "O mistério é a coisa mais bela que podemos experimentar. É a fonte de toda verdadeira arte e ciência.", source: "Albert Einstein", reflection: "Einstein se considerava agnóstico. O mistério do universo não precisa de respostas — pode ser apreciado.", study: "Einstein descrevia seu sentimento como 'religiosidade cósmica' — admiração pelo mistério do universo sem atribuí-lo a um deus pessoal.", practice: "Contemple algo misterioso hoje: o céu estrelado, a complexidade do cérebro, a origem da consciência. Aprecie sem precisar explicar." },
    { verse: "Duvidar é a condição humana. Ter paz com a dúvida é sabedoria.", source: "Reflexão agnóstica", reflection: "Não ter todas as respostas não impede uma vida plena e ética.", study: "O agnosticismo saudável não é paralisia diante da dúvida, mas liberdade para explorar sem dogmas. Thomas Huxley cunhou o termo em 1869.", practice: "Faça uma lista de coisas que você não sabe e está tudo bem não saber. Sinta a leveza de não precisar ter certeza de tudo." },
    { verse: "A bondade é a linguagem que os surdos podem ouvir e os cegos podem ver.", source: "Mark Twain", reflection: "A bondade transcende crenças, culturas e idiomas. É universalmente compreendida.", study: "A ética pode ser fundamentada na experiência humana compartilhada. Empatia, compaixão e bondade são valores que independem de posição metafísica.", practice: "Pratique um ato de bondade radical hoje: ajude um estranho, perdoe uma ofensa, doe seu tempo." },
    { verse: "Não tenho obrigação de ter certeza. Tenho o dever de ser honesta.", source: "Reflexão agnóstica", reflection: "A honestidade intelectual — admitir que não sabe — é mais corajosa que falsa certeza.", study: "O agnosticismo honesto reconhece que algumas perguntas podem não ter resposta definitiva nesta vida. Isso não paralisa — liberta para viver com integridade.", practice: "Hoje, quando perguntarem sua opinião sobre algo que não sabe, diga honestamente: 'Não sei.' Sinta a liberdade disso." },
    { verse: "O universo não tem obrigação de fazer sentido para você.", source: "Neil deGrasse Tyson", reflection: "Aceitar que nem tudo faz sentido é libertador. O universo é maior que nossa compreensão.", study: "A humildade cósmica reconhece que o universo observável tem 93 bilhões de anos-luz e nós ocupamos um ponto ínfimo. Isso pode ser aterrorizante ou maravilhoso.", practice: "Aceite algo que não faz sentido na sua vida sem tentar forçar uma explicação. Às vezes, simplesmente é o que é." },
  ],
  universal: [
    { verse: "Seja a mudança que você deseja ver no mundo.", source: "Mahatma Gandhi", reflection: "A transformação coletiva começa com a individual. Suas escolhas diárias moldam o mundo.", study: "Gandhi praticou a mudança pessoal como ferramenta política e espiritual. Sua filosofia de satyagraha (força da verdade) mostra que transformação interior gera transformação social.", practice: "Identifique uma mudança positiva que você quer ver e pratique-a hoje em sua própria vida." },
    { verse: "A gratidão transforma o que temos em suficiente.", source: "Melody Beattie", reflection: "Quando focamos no que já possuímos, a escassez dá lugar à abundância interior.", study: "Pesquisas em psicologia positiva mostram que a prática regular de gratidão aumenta a felicidade em até 25% e reduz sintomas de depressão.", practice: "Escreva 3 coisas pelas quais você é grata hoje. Releia antes de dormir e sinta a gratidão no coração." },
    { verse: "Em um mundo onde você pode ser qualquer coisa, seja gentil.", source: "Sabedoria popular", reflection: "A gentileza é uma escolha poderosa que transforma relações e ambientes.", study: "Estudos mostram que atos de gentileza liberam ocitocina e serotonina tanto em quem pratica quanto em quem recebe — e até em quem observa.", practice: "Pratique 3 atos de gentileza aleatória hoje: abra a porta para alguém, elogie, ajude sem ser pedida." },
    { verse: "O que te preocupa te domina.", source: "John Locke", reflection: "A preocupação excessiva é uma prisão mental. Foque no que está ao seu alcance.", study: "Os estoicos ensinavam a distinguir entre o que está sob nosso controle (ações, pensamentos) e o que não está (eventos externos). Focar no primeiro traz serenidade.", practice: "Liste suas preocupações. Separe: o que posso controlar × o que não posso. Aja no primeiro grupo e solte o segundo." },
    { verse: "A compaixão é a base de toda moralidade.", source: "Arthur Schopenhauer", reflection: "Sentir a dor do outro e agir para aliviá-la é a essência de toda ética verdadeira.", study: "Schopenhauer argumentou que a compaixão — a capacidade de sentir com o outro — é a única motivação moral genuína. Todas as tradições espirituais concordam.", practice: "Quando encontrar alguém sofrendo hoje, não apenas simpatize — aja. Ofereça ajuda concreta, escuta ou presença." },
    { verse: "Não é o mais forte que sobrevive, nem o mais inteligente, mas o mais adaptável à mudança.", source: "Inspirado em Darwin", reflection: "A capacidade de se adaptar é a maior força que você pode desenvolver.", study: "A resiliência — capacidade de se adaptar e recuperar de adversidades — é uma das habilidades mais estudadas na psicologia moderna.", practice: "Identifique uma mudança que está resistindo. Pergunte: 'Como posso me adaptar a isso em vez de lutar contra?'" },
    { verse: "Eu sustento que a humanidade é mais bem servida quando nos dedicamos ao amor e à compaixão.", source: "Albert Einstein", reflection: "Independente de crenças, amor e compaixão são valores universais que nos conectam.", study: "Todas as grandes tradições — religiosas, filosóficas e humanistas — convergem para o amor e a compaixão como valores supremos.", practice: "Dedique este dia ao amor prático: ame seus próximos, ame estranhos, ame a si mesma. O amor em ação muda tudo." },
  ],
};

function getDayOfYear(date: Date): number {
  return Math.floor((date.getTime() - new Date(date.getFullYear(), 0, 0).getTime()) / 86400000);
}

function getDevotionalForDate(religion: Religion, date: Date): Devotional {
  const list = devotionalsByReligion[religion] || devotionalsByReligion["universal"];
  if (!list || list.length === 0) {
    return { verse: "Que este dia seja cheio de luz e propósito.", source: "Reflexão do dia", reflection: "Cada dia é uma oportunidade de crescer.", study: "A prática diária de reflexão fortalece a mente e o espírito.", practice: "Dedique 5 minutos ao silêncio e gratidão." };
  }
  const dayIndex = getDayOfYear(date) % list.length;
  return list[dayIndex];
}

export default function DailyDevotional() {
  const [religion, setReligion] = useState<Religion | null>(() => {
    const saved = localStorage.getItem("user-religion") as Religion | null;
    if (saved && religionLabels[saved]) return saved;
    return null;
  });

  const [viewDate, setViewDate] = useState(new Date());

  useEffect(() => {
    if (religion) localStorage.setItem("user-religion", religion);
  }, [religion]);

  const goBack = () => setViewDate((d) => subDays(d, 1));
  const goForward = () => { if (!isToday(viewDate)) setViewDate((d) => addDays(d, 1)); };

  if (!religion) {
    return (
      <section className="rounded-2xl border border-border bg-card p-5 space-y-4 shadow-sm">
        <div className="flex items-center gap-2">
          <BookMarked className="h-4 w-4 text-primary" />
          <p className="text-[10px] font-body tracking-[0.2em] uppercase text-primary">Palavra do Dia</p>
        </div>
        <p className="text-sm font-body text-card-foreground leading-relaxed">
          Para personalizar sua palavra do dia, selecione sua orientação espiritual:
        </p>
        <div className="grid grid-cols-2 gap-2 max-h-[320px] overflow-y-auto pr-1">
          {(Object.entries(religionLabels) as [Religion, string][]).map(([key, label]) => (
            <button
              key={key}
              onClick={() => setReligion(key)}
              className="rounded-xl border border-border bg-background px-2 py-2 text-xs font-body text-card-foreground hover:border-primary hover:bg-primary/5 transition-colors text-center"
            >
              {label}
            </button>
          ))}
        </div>
      </section>
    );
  }

  const devotional = getDevotionalForDate(religion, viewDate);
  const dateLabel = isToday(viewDate) ? "Hoje" : format(viewDate, "dd 'de' MMMM", { locale: ptBR });

  return (
    <section className="rounded-2xl border border-border bg-card p-5 space-y-4 shadow-sm">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <BookMarked className="h-4 w-4 text-primary" />
          <p className="text-[10px] font-body tracking-[0.2em] uppercase text-primary">Palavra do Dia</p>
        </div>
        <Select value={religion} onValueChange={(v) => setReligion(v as Religion)}>
          <SelectTrigger className="h-7 w-auto max-w-[140px] gap-1 border-none bg-muted/50 px-2 text-[10px] font-body text-muted-foreground">
            <SelectValue />
          </SelectTrigger>
          <SelectContent className="max-h-60">
            {(Object.entries(religionLabels) as [Religion, string][]).map(([key, label]) => (
              <SelectItem key={key} value={key} className="text-xs">{label}</SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      {/* Date navigation */}
      <div className="flex items-center justify-center gap-3">
        <Button variant="ghost" size="icon" className="h-7 w-7" onClick={goBack}>
          <ChevronLeft className="h-4 w-4" />
        </Button>
        <span className="text-xs font-body text-muted-foreground flex items-center gap-1">
          <History className="h-3 w-3" /> {dateLabel}
        </span>
        <Button variant="ghost" size="icon" className="h-7 w-7" onClick={goForward} disabled={isToday(viewDate)}>
          <ChevronRight className="h-4 w-4" />
        </Button>
      </div>

      <p className="text-base font-display font-medium text-card-foreground leading-relaxed italic">"{devotional.verse}"</p>
      <p className="text-[10px] font-body text-primary font-semibold">— {devotional.source}</p>

      <div className="space-y-3 border-t border-border pt-3">
        <div>
          <p className="text-[10px] font-body tracking-[0.2em] uppercase text-muted-foreground mb-1">Reflexão</p>
          <p className="text-sm font-body text-muted-foreground leading-relaxed">{devotional.reflection}</p>
        </div>
        <div>
          <p className="text-[10px] font-body tracking-[0.2em] uppercase text-muted-foreground mb-1">📖 Estudo da Palavra</p>
          <p className="text-sm font-body text-muted-foreground leading-relaxed">{devotional.study}</p>
        </div>
        <div>
          <p className="text-[10px] font-body tracking-[0.2em] uppercase text-muted-foreground mb-1">🙏 Prática do Dia</p>
          <p className="text-sm font-body text-muted-foreground leading-relaxed">{devotional.practice}</p>
        </div>
      </div>
    </section>
  );
}
